-- Item U: re-grant SELECT + INSERT on workspace_members to
-- nosdesk_app so the cookie auth gate can read memberships and
-- user-creation flows can add new rows. UPDATE + DELETE stay
-- REVOKE'd so membership lifecycle (promote / demote / remove)
-- still requires explicit elevation via PlatformConn.
--
-- The 3h.6 grant tightening REVOKE'd all four privileges. The
-- design reasoning was "membership management is admin-only" -
-- which is right for management, but read+insert at
-- user-creation time are system operations tightly coupled to
-- the user lifecycle, not admin actions.
--
-- Without these grants the gate fails closed (`permission
-- denied for table workspace_members`) on every authenticated
-- request and every user-creation path errors mid-transaction.
-- With them, the lockdown is narrowed to UPDATE / DELETE -
-- still meaningful, since changing a user's role within a
-- workspace or removing them entirely is the management surface
-- 3h.6 was protecting.

GRANT SELECT, INSERT ON workspace_members TO nosdesk_app;
