-- Adds the `merged` value to the workflow_state_category enum so a
-- ticket consumed by a merge can sit in a dedicated terminal state,
-- distinct from `done` (resolved) and `cancelled`. The enum value and
-- the workflow_states row that uses it are split across two migrations
-- on purpose: Postgres forbids using a newly added enum label in the
-- same transaction that adds it, and Diesel wraps each migration in its
-- own transaction.
--
-- IF NOT EXISTS keeps `diesel migration redo` idempotent, since the
-- down migration cannot remove an enum label (see down.sql).
ALTER TYPE workflow_state_category ADD VALUE IF NOT EXISTS 'merged';
