use chrono::Utc;
use diesel::prelude::*;
use ring::aead::{Aad, LessSafeKey, Nonce, UnboundKey, AES_256_GCM, NONCE_LEN};
use ring::pbkdf2;
use ring::rand::{SecureRandom, SystemRandom};
use std::collections::HashMap;
use std::fs::{self, File};
use std::io::{Read, Write};
use std::path::{Path, PathBuf};
use uuid::Uuid;
use walkdir::WalkDir;
use zip::write::SimpleFileOptions;
use zip::{ZipArchive, ZipWriter};

pub use super::backup_upgrade::NotRestorable;
use super::backup_upgrade::SchemaPoint;
use crate::db::DbConnection;
use crate::models::{
    BackupJobUpdate, BackupManifest, FilesManifest, RestorePreview, RestoreUpgrade, TableManifest,
};
use crate::repository::backup as backup_repo;

// Encryption constants. AES-256-GCM + PBKDF2-HMAC-SHA256 are the
// same primitives the MFA encryption path uses; reusing them keeps
// the crypto surface area small.
const SALT_LENGTH: usize = 32;
// OWASP's current floor for PBKDF2-HMAC-SHA256. Bumped from 100_000;
// the decrypt path hard-rejects any format-version mismatch (no archive
// format restores under another), so BACKUP_FORMAT_VERSION is bumped in
// lockstep below — an older backup encrypted at the previous iteration
// count gets a clean "unsupported version" error instead of a cryptic
// GCM auth failure. See security-audit-2026-06.
const PBKDF2_ITERATIONS: u32 = 600_000;

/// Outer wrapper magic — 4 bytes prepended to encrypted backups so
/// the reader can tell at a glance whether to decrypt before
/// parsing. A plaintext backup IS a zip (starts with `PK\x03\x04`)
/// and skips this wrapper entirely.
const ENCRYPTED_MAGIC: &[u8; 4] = b"NODB";

/// Outer wrapper header: 4 magic + 4 format-version + 32 salt + 12 nonce.
const ENCRYPTED_HEADER_LEN: usize = 4 + 4 + SALT_LENGTH + NONCE_LEN;

/// Current on-disk backup format. Bumped only on breaking changes
/// to the wire shape (manifest schema, encryption envelope, etc.).
/// v2 raised the PBKDF2 iteration count (see PBKDF2_ITERATIONS); the
/// field lets the reader refuse archives it can't parse rather than
/// fail cryptically.
const BACKUP_FORMAT_VERSION: u32 = 2;

/// `build.rs`'s fingerprint of the migrations, still written to the
/// manifest's `schema_hash`. Restore goes by `migration_version` and
/// `schema_sha256` instead (see `backup_upgrade`).
const SERVER_SCHEMA_HASH: &str = env!("NOSDESK_SCHEMA_HASH");

/// Fields that contain authentication material. Stripped from
/// plaintext (no-password) backups so a leaked zip can't be used
/// to recover credentials. Encrypted backups include them
/// normally — the whole archive is sealed by AES-GCM, so a
/// sidecar would just add complexity for no gain. Restore loads
/// a plaintext backup without them (`MISSING_COLUMNS`).
pub(crate) const SENSITIVE_FIELDS: &[(&str, &[&str])] = &[
    ("users", &["mfa_secret"]),
    ("user_recovery_codes", &["code_hash"]),
    ("user_auth_identities", &["password_hash", "metadata"]),
    ("refresh_tokens", &["token_hash"]),
    ("reset_tokens", &["token_hash", "metadata"]),
    // The webhook secret is the plaintext HMAC signing key, and the
    // custom headers commonly carry an Authorization value for the
    // receiver. Both would let a reader of a plaintext backup forge
    // signed deliveries / harvest receiver credentials. See
    // security-audit-2026-06.
    ("webhooks", &["secret", "headers"]),
    // SHA-256 of a 128-bit random token: low impact, but stripping it
    // keeps parity with refresh_tokens.token_hash above.
    ("api_tokens", &["token_hash"]),
];

/// Tables to export in backup
/// Tables to skip during backup discovery.
///
/// The list is exhaustive (and tested below) — every other
/// public-schema base table in the running DB ends up in the
/// backup, including any tables added by future migrations. This
/// is the Discourse / Supabase pattern: enumerate from
/// `information_schema`, then subtract the small set of tables
/// that are genuinely derivable from the running system rather
/// than from operator data.
///
/// Specifically NOT excluded (despite being tempting):
///   - `outbound_emails`: in-flight queue rows are user-relevant.
///     A backup taken mid-failure should retain queued retries.
///   - `webhook_deliveries`: same reasoning.
///   - `sync_actions`: the trigger-driven outbox. Empty most of
///     the time, but a backup-mid-burst can legitimately carry
///     in-flight events; the consumer worker is idempotent.
const EXCLUDE_FROM_BACKUP: &[&str] = &[
    // Diesel's own migration ledger. Regenerated by
    // `diesel migration run` on restore; including it would
    // re-run no-op migrations and possibly conflict on a server
    // that's already a step ahead.
    "__diesel_schema_migrations",
];

/// Discover the set of tables to back up by introspecting
/// `information_schema.tables`. Replaces the previous hardcoded
/// `BACKUP_TABLES` const that silently dropped any table added by
/// a migration but not added to the list (the AUD-014 bug class:
/// channels, outbound_emails, email_bounces all missed). Result
/// is sorted alphabetically for stable backup output across runs.
fn discover_user_tables(conn: &mut DbConnection) -> Result<Vec<String>, BackupError> {
    use diesel::deserialize::QueryableByName;
    use diesel::prelude::*;
    use diesel::sql_query;
    use diesel::sql_types::Text;

    #[derive(QueryableByName)]
    struct TableName {
        #[diesel(sql_type = Text)]
        table_name: String,
    }

    // Ordinary tables and partitioned parents only. Partition
    // children are excluded; the parent's row set covers them
    // and dumping both duplicates the data.
    let rows: Vec<TableName> = sql_query(
        "SELECT c.relname AS table_name \
         FROM pg_class c \
         JOIN pg_namespace n ON n.oid = c.relnamespace \
         WHERE n.nspname = 'public' \
           AND c.relkind IN ('r','p') \
           AND c.relispartition = false \
         ORDER BY c.relname",
    )
    .load(conn)
    .map_err(BackupError::DatabaseError)?;

    Ok(rows
        .into_iter()
        .map(|r| r.table_name)
        .filter(|t| !EXCLUDE_FROM_BACKUP.contains(&t.as_str()))
        .collect())
}

/// Names of partition-child tables in the public schema. The
/// restore path skips these because their rows arrive via the
/// parent table's payload.
fn partition_children(
    conn: &mut DbConnection,
) -> Result<std::collections::HashSet<String>, BackupError> {
    use diesel::deserialize::QueryableByName;
    use diesel::prelude::*;
    use diesel::sql_query;
    use diesel::sql_types::Text;

    #[derive(QueryableByName)]
    struct TableName {
        #[diesel(sql_type = Text)]
        table_name: String,
    }

    let rows: Vec<TableName> = sql_query(
        "SELECT c.relname AS table_name \
         FROM pg_class c \
         JOIN pg_namespace n ON n.oid = c.relnamespace \
         WHERE n.nspname = 'public' \
           AND c.relkind = 'r' \
           AND c.relispartition = true",
    )
    .load(conn)
    .map_err(BackupError::DatabaseError)?;

    Ok(rows.into_iter().map(|r| r.table_name).collect())
}

/// Defence-in-depth check used by `export_table_data` and the
/// restore path. Returns true only for tables actually present
/// in `information_schema.tables` for the public schema, so a
/// poisoned backup file (or a future caller bug) can't trick
/// the writer into interpolating an arbitrary identifier into
/// SQL.
pub(crate) fn table_exists_in_db(
    conn: &mut DbConnection,
    table_name: &str,
) -> Result<bool, BackupError> {
    use diesel::deserialize::QueryableByName;
    use diesel::prelude::*;
    use diesel::sql_query;
    use diesel::sql_types::{Bool, Text};

    #[derive(QueryableByName)]
    struct ExistsRow {
        #[diesel(sql_type = Bool)]
        exists: bool,
    }

    let row: ExistsRow = sql_query(
        "SELECT EXISTS ( \
            SELECT 1 FROM information_schema.tables \
            WHERE table_schema = 'public' \
              AND table_type = 'BASE TABLE' \
              AND table_name = $1 \
        ) AS exists",
    )
    .bind::<Text, _>(table_name)
    .get_result(conn)
    .map_err(BackupError::DatabaseError)?;
    Ok(row.exists)
}

/// Error type for backup operations
#[derive(Debug)]
pub enum BackupError {
    IoError(std::io::Error),
    ZipError(zip::result::ZipError),
    JsonError(serde_json::Error),
    DatabaseError(diesel::result::Error),
    EncryptionError(String),
    InvalidPassword,
    CorruptedBackup(String),
    /// `MIGRATION_DATABASE_URL` is set and no connection to it opened.
    /// Carries the cause, which names the host and user, so it stays out of
    /// the message: see [`BackupError::connection_cause`].
    MigrationRoleUnreachable(String),
    /// No database connection to restore on. Carries the cause, as above.
    ConnectionUnavailable(String),
    /// The backup's schema isn't one this build can restore.
    NotRestorable(super::backup_upgrade::NotRestorable),
    /// An older backup is upgraded in a scratch database built from the
    /// first migration, which takes a superuser, and the role restore runs
    /// as isn't one.
    NeedsSuperuser,
    /// Another restore of this database is running.
    RestoreInProgress,
    /// Upgrading an older backup's rows to this build's schema failed.
    UpgradeFailed(String),
}

impl BackupError {
    /// No connection to restore on: the database is out of reach, not the
    /// archive at fault.
    pub fn is_connection(&self) -> bool {
        self.connection_cause().is_some()
    }

    /// Why no connection opened, for the operator's own terminal (the CLI)
    /// and the log. Never in a response or a stored message: it names the
    /// database host and user.
    pub fn connection_cause(&self) -> Option<&str> {
        match self {
            BackupError::MigrationRoleUnreachable(cause)
            | BackupError::ConnectionUnavailable(cause) => Some(cause),
            _ => None,
        }
    }
}

impl std::fmt::Display for BackupError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            BackupError::IoError(e) => write!(f, "IO error: {e}"),
            BackupError::ZipError(e) => write!(f, "ZIP error: {e}"),
            BackupError::JsonError(e) => write!(f, "JSON error: {e}"),
            BackupError::DatabaseError(e) => write!(f, "Database error: {e}"),
            BackupError::EncryptionError(e) => write!(f, "Encryption error: {e}"),
            BackupError::InvalidPassword => write!(f, "Invalid password"),
            BackupError::CorruptedBackup(e) => write!(f, "Corrupted backup: {e}"),
            BackupError::MigrationRoleUnreachable(_) => {
                write!(f, "MIGRATION_DATABASE_URL is set but couldn't connect")
            }
            BackupError::ConnectionUnavailable(_) => write!(f, "Database connection unavailable"),
            BackupError::NotRestorable(reason) => write!(f, "Can't restore: {reason}"),
            BackupError::NeedsSuperuser => write!(
                f,
                "Restoring a backup from an earlier Nosdesk version upgrades it in a temporary \
                 database built the way a fresh install is, which needs a superuser role, as a \
                 fresh install does. The role restore runs as (MIGRATION_DATABASE_URL, or \
                 DATABASE_URL when that isn't set) isn't one. Nothing was changed. See \
                 https://nosdesk.com/docs/operations/backup-restore#restoring-a-backup-from-an-earlier-version"
            ),
            BackupError::RestoreInProgress => write!(
                f,
                "Another restore of this database is running. Wait for it to finish, then check \
                 the result before restoring again."
            ),
            BackupError::UpgradeFailed(e) => write!(f, "Upgrading the backup failed: {e}"),
        }
    }
}

impl From<std::io::Error> for BackupError {
    fn from(e: std::io::Error) -> Self {
        BackupError::IoError(e)
    }
}

impl From<zip::result::ZipError> for BackupError {
    fn from(e: zip::result::ZipError) -> Self {
        BackupError::ZipError(e)
    }
}

impl From<serde_json::Error> for BackupError {
    fn from(e: serde_json::Error) -> Self {
        BackupError::JsonError(e)
    }
}

impl From<diesel::result::Error> for BackupError {
    fn from(e: diesel::result::Error) -> Self {
        BackupError::DatabaseError(e)
    }
}

/// Derive encryption key from password using PBKDF2
fn derive_key(password: &str, salt: &[u8]) -> [u8; 32] {
    let mut key = [0u8; 32];
    pbkdf2::derive(
        pbkdf2::PBKDF2_HMAC_SHA256,
        std::num::NonZeroU32::new(PBKDF2_ITERATIONS).unwrap(),
        salt,
        password.as_bytes(),
        &mut key,
    );
    key
}

/// Encrypt data using AES-256-GCM (same pattern as MFA encryption)
fn encrypt_data(data: &[u8], key: &[u8; 32]) -> Result<(Vec<u8>, [u8; NONCE_LEN]), BackupError> {
    let unbound_key = UnboundKey::new(&AES_256_GCM, key)
        .map_err(|_| BackupError::EncryptionError("Failed to create encryption key".to_string()))?;
    let sealing_key = LessSafeKey::new(unbound_key);

    // Generate random nonce
    let rng = SystemRandom::new();
    let mut nonce_bytes = [0u8; NONCE_LEN];
    rng.fill(&mut nonce_bytes)
        .map_err(|_| BackupError::EncryptionError("Failed to generate nonce".to_string()))?;
    let nonce = Nonce::assume_unique_for_key(nonce_bytes);

    // Encrypt the data
    let mut in_out = data.to_vec();
    sealing_key
        .seal_in_place_append_tag(nonce, Aad::empty(), &mut in_out)
        .map_err(|_| BackupError::EncryptionError("Encryption failed".to_string()))?;

    Ok((in_out, nonce_bytes))
}

/// Wrap a plaintext inner-zip blob in the encrypted outer
/// envelope: `NODB` magic, format version, fresh salt, fresh
/// nonce, then the AES-GCM ciphertext. The header is plaintext
/// by design so the reader can recognise the file before having
/// the password; everything that could leak schema info or row
/// counts lives inside the ciphertext.
pub(crate) fn seal_inner_zip(inner_zip: &[u8], password: &str) -> Result<Vec<u8>, BackupError> {
    let rng = SystemRandom::new();
    let mut salt = [0u8; SALT_LENGTH];
    rng.fill(&mut salt)
        .map_err(|_| BackupError::EncryptionError("Failed to generate salt".to_string()))?;

    let key = derive_key(password, &salt);
    let (ciphertext, nonce) = encrypt_data(inner_zip, &key)?;

    let mut out = Vec::with_capacity(ENCRYPTED_HEADER_LEN + ciphertext.len());
    out.extend_from_slice(ENCRYPTED_MAGIC);
    out.extend_from_slice(&BACKUP_FORMAT_VERSION.to_le_bytes());
    out.extend_from_slice(&salt);
    out.extend_from_slice(&nonce);
    out.extend_from_slice(&ciphertext);
    Ok(out)
}

/// Parse the encrypted outer envelope and return the plaintext
/// inner-zip bytes. The header is validated up front so a
/// malformed file fails fast with a clear error instead of a
/// generic decryption failure.
pub(crate) fn unseal_inner_zip(file_bytes: &[u8], password: &str) -> Result<Vec<u8>, BackupError> {
    if file_bytes.len() < ENCRYPTED_HEADER_LEN {
        return Err(BackupError::CorruptedBackup(
            "encrypted backup is shorter than its header".to_string(),
        ));
    }
    if &file_bytes[0..4] != ENCRYPTED_MAGIC {
        return Err(BackupError::CorruptedBackup(
            "missing NODB magic on encrypted backup".to_string(),
        ));
    }
    let version = u32::from_le_bytes(file_bytes[4..8].try_into().unwrap());
    if version != BACKUP_FORMAT_VERSION {
        return Err(BackupError::CorruptedBackup(format!(
            "unsupported backup format version {version}; this build expects {BACKUP_FORMAT_VERSION}"
        )));
    }
    let mut salt = [0u8; SALT_LENGTH];
    let mut nonce = [0u8; NONCE_LEN];
    salt.copy_from_slice(&file_bytes[8..8 + SALT_LENGTH]);
    nonce.copy_from_slice(&file_bytes[8 + SALT_LENGTH..ENCRYPTED_HEADER_LEN]);

    let key = derive_key(password, &salt);
    decrypt_data(&file_bytes[ENCRYPTED_HEADER_LEN..], &key, &nonce)
}

/// True when the file starts with the encrypted-wrapper magic.
/// Cheap byte check; callers use this to decide whether to
/// require a password.
pub fn is_encrypted_backup(backup_path: &Path) -> Result<bool, BackupError> {
    use std::io::Read as _;
    let mut f = File::open(backup_path)?;
    let mut magic = [0u8; 4];
    match f.read_exact(&mut magic) {
        Ok(()) => Ok(&magic == ENCRYPTED_MAGIC),
        // Shorter than 4 bytes — definitely not one of ours; let
        // the zip reader fail with its own message.
        Err(_) => Ok(false),
    }
}

/// Load the backup's inner zip bytes into memory. For plaintext
/// backups this is just the file contents; for encrypted ones
/// it's the result of unsealing the wrapper.
///
/// The whole zip lives in memory after this returns. That's
/// acceptable because the existing flow (which read every
/// `data/*.json` and `files/*` entry through `ZipArchive::by_name`)
/// already paged it all in, just with the kernel doing the work
/// instead of us.
fn load_inner_zip(backup_path: &Path, password: Option<&str>) -> Result<Vec<u8>, BackupError> {
    if is_encrypted_backup(backup_path)? {
        let bytes = fs::read(backup_path)?;
        let password = password.ok_or_else(|| {
            BackupError::EncryptionError("backup is encrypted; password is required".to_string())
        })?;
        unseal_inner_zip(&bytes, password)
    } else {
        Ok(fs::read(backup_path)?)
    }
}

/// Decrypt data using AES-256-GCM
fn decrypt_data(
    encrypted_data: &[u8],
    key: &[u8; 32],
    nonce_bytes: &[u8; NONCE_LEN],
) -> Result<Vec<u8>, BackupError> {
    let unbound_key = UnboundKey::new(&AES_256_GCM, key)
        .map_err(|_| BackupError::EncryptionError("Failed to create decryption key".to_string()))?;
    let opening_key = LessSafeKey::new(unbound_key);

    let nonce = Nonce::try_assume_unique_for_key(nonce_bytes)
        .map_err(|_| BackupError::EncryptionError("Invalid nonce".to_string()))?;

    // Decrypt
    let mut in_out = encrypted_data.to_vec();
    let plaintext = opening_key
        .open_in_place(nonce, Aad::empty(), &mut in_out)
        .map_err(|_| BackupError::InvalidPassword)?;

    Ok(plaintext.to_vec())
}

/// Export table data as JSON using raw SQL.
///
/// `table_name` is interpolated into the query directly because
/// Postgres doesn't accept identifiers as bound parameters. The
/// caller is responsible for passing only names that came from
/// `discover_user_tables`; we additionally validate against
/// `information_schema.tables` here as defence in depth so a
/// future caller can't accidentally widen the SQL-injection
/// surface.
/// Export one table's rows as a JSON-text payload. The row JSON
/// never passes through serde_json::Value, so numeric precision
/// (NUMERIC(12,3) → "10.000") is preserved verbatim. Sensitive-
/// field stripping runs inside Postgres via the `jsonb - 'key'`
/// operator.
fn export_table_data(
    conn: &mut DbConnection,
    table_name: &str,
    include_sensitive: bool,
) -> Result<(String, i64), BackupError> {
    use diesel::sql_query;
    use diesel::sql_types::Text;

    if !table_exists_in_db(conn, table_name)? {
        return Err(BackupError::CorruptedBackup(format!(
            "Refusing to export unknown table: {table_name}"
        )));
    }

    // Decide the per-row projection. With sensitive stripping,
    // the row goes through ::jsonb so the `- 'key'` operator can
    // run; back to ::text at the end for the wire format.
    let strip_fields: &[&str] = if include_sensitive {
        &[]
    } else {
        SENSITIVE_FIELDS
            .iter()
            .find(|(t, _)| *t == table_name)
            .map(|(_, fields)| *fields)
            .unwrap_or(&[])
    };

    let row_expr = if strip_fields.is_empty() {
        "row_to_json(t)::text".to_string()
    } else {
        let mut expr = "row_to_json(t)::jsonb".to_string();
        for f in strip_fields {
            // The stripped names come from the SENSITIVE_FIELDS
            // const so the value is fully under our control. We
            // still escape any embedded single quotes defensively.
            let escaped = f.replace('\'', "''");
            expr.push_str(&format!(" - '{escaped}'"));
        }
        format!("({expr})::text")
    };

    #[derive(QueryableByName)]
    struct JsonRow {
        #[diesel(sql_type = Text)]
        row_text: String,
    }

    let query = format!("SELECT {row_expr} AS row_text FROM {table_name} t");
    let results: Vec<JsonRow> = sql_query(&query).load(conn)?;

    // Assemble a JSON array as text. Each row_text is already a
    // valid JSON object (or null for empty rows, which shouldn't
    // happen). Joining with `,\n  ` keeps the on-disk format
    // mirror-image to the old pretty-printed output.
    let mut payload = String::from("[");
    for (i, row) in results.iter().enumerate() {
        if i > 0 {
            payload.push(',');
        }
        payload.push_str("\n  ");
        payload.push_str(&row.row_text);
    }
    if !results.is_empty() {
        payload.push('\n');
    }
    payload.push(']');

    let count = results.len() as i64;
    Ok((payload, count))
}

/// Get the uploads directory path
pub(crate) fn get_uploads_dir() -> PathBuf {
    std::env::var("UPLOAD_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("/app/uploads"))
}

/// Get the backups directory path
fn get_backups_dir() -> PathBuf {
    let base = std::env::var("UPLOAD_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("/app/uploads"));
    base.join("backups")
}

/// SHA-256 of arbitrary bytes, returned as lowercase hex. Used
/// for per-table integrity hashes in the backup manifest.
pub(crate) fn sha256_hex(bytes: &[u8]) -> String {
    use ring::digest::{digest, SHA256};
    hex::encode(digest(&SHA256, bytes).as_ref())
}

/// Create a backup export.
///
/// Builds the zip in memory and writes it to disk in one go.
/// When `password` is `Some`, the bytes are wrapped in the
/// AES-GCM envelope before writing (so the on-disk file is
/// `NODB...`). When `password` is `None`, the zip is written
/// as-is and sensitive fields are stripped from each table's
/// JSON.
pub fn create_backup(
    conn: &mut DbConnection,
    job_id: Uuid,
    password: Option<&str>,
) -> Result<PathBuf, BackupError> {
    let backups_dir = get_backups_dir();
    fs::create_dir_all(&backups_dir)?;

    // Microsecond resolution so concurrent backup calls (test
    // parallelism, fast successive admin clicks) don't collide
    // on the on-disk filename.
    let timestamp = Utc::now().format("%Y-%m-%d-%H%M%S-%6f");
    // Encrypted backups still carry the `.zip` extension because
    // the wrapped inner format IS a zip; the only difference is
    // the 52-byte header. Operators can still tell them apart
    // with `file` (zip vs data) but the extension stays familiar.
    let filename = format!("backup-{timestamp}.zip");
    let backup_path = backups_dir.join(&filename);

    let include_sensitive = password.is_some();
    let zip_bytes = build_inner_zip(conn, include_sensitive, true)?;

    let final_bytes = match password {
        Some(pw) => seal_inner_zip(&zip_bytes, pw)?,
        None => zip_bytes,
    };
    fs::write(&backup_path, &final_bytes)?;

    let file_size = final_bytes.len() as i64;
    backup_repo::update_backup_job(
        conn,
        job_id,
        BackupJobUpdate {
            status: Some("completed".to_string()),
            file_path: Some(backup_path.to_string_lossy().to_string()),
            file_size: Some(file_size),
            error_message: None,
            completed_at: Some(Utc::now().naive_utc()),
        },
    )?;

    Ok(backup_path)
}

/// Build the inner zip blob (the thing that gets either written
/// straight to disk or sealed by `seal_inner_zip`). Encapsulated
/// here so `create_backup` is small and the in-memory pipeline
/// is easy to audit. `include_files` leaves the uploads out, for the
/// rows-only archive an older backup is upgraded into.
pub(crate) fn build_inner_zip(
    conn: &mut DbConnection,
    include_sensitive: bool,
    include_files: bool,
) -> Result<Vec<u8>, BackupError> {
    use std::io::Cursor;

    // Owned cursor over a Vec<u8> so we can pull the buffer back
    // out of the writer via `finish()` without lifetime gymnastics.
    let cursor: Cursor<Vec<u8>> = Cursor::new(Vec::new());
    let mut zip = ZipWriter::new(cursor);
    let options = SimpleFileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated)
        .unix_permissions(0o644);

    let mut table_manifests = HashMap::new();
    let tables_to_export = discover_user_tables(conn)?;

    for table_name in &tables_to_export {
        let table_name: &str = table_name;
        let (json_content, count) = export_table_data(conn, table_name, include_sensitive)?;
        let sha256 = sha256_hex(json_content.as_bytes());

        let path = format!("data/{table_name}.json");
        zip.start_file(&path, options)?;
        zip.write_all(json_content.as_bytes())?;

        table_manifests.insert(table_name.to_string(), TableManifest { count, sha256 });
    }

    // Files. Same skip-rules as before: avoid recursing into our
    // own backups dir, and skip thumbnails (cheap to regenerate
    // from the originals).
    let uploads_dir = get_uploads_dir();
    let mut file_count = 0i64;
    let mut total_size = 0i64;

    if include_files && uploads_dir.exists() {
        let thumbs_dir = uploads_dir.join("users").join("thumbs");
        for entry in WalkDir::new(&uploads_dir)
            .into_iter()
            .filter_entry(|e| {
                let path = e.path();
                !path.starts_with(get_backups_dir()) && !path.starts_with(&thumbs_dir)
            })
            .filter_map(|e| e.ok())
        {
            if entry.file_type().is_file() {
                let file_path = entry.path();
                let relative_path = file_path
                    .strip_prefix(&uploads_dir)
                    .map_err(|e| BackupError::IoError(std::io::Error::other(e.to_string())))?;
                let archive_path = format!("files/{}", relative_path.display());

                zip.start_file(&archive_path, options)?;
                let mut file = File::open(file_path)?;
                let mut buf = Vec::new();
                let size = file.read_to_end(&mut buf)?;
                zip.write_all(&buf)?;

                file_count += 1;
                total_size += size as i64;
            }
        }
    }

    let manifest = BackupManifest {
        backup_format_version: BACKUP_FORMAT_VERSION,
        nosdesk_version: env!("CARGO_PKG_VERSION").to_string(),
        schema_hash: SERVER_SCHEMA_HASH.to_string(),
        migration_version: Some(super::backup_upgrade::current_schema().version.to_string()),
        schema_sha256: Some(super::backup_upgrade::current_schema().sha256.to_string()),
        created_at: Utc::now().to_rfc3339(),
        tables: table_manifests,
        files: FilesManifest {
            total_count: file_count,
            total_size_bytes: total_size,
        },
    };

    let manifest_json = serde_json::to_string_pretty(&manifest)?;
    zip.start_file("manifest.json", options)?;
    zip.write_all(manifest_json.as_bytes())?;
    let finished = zip.finish()?;
    Ok(finished.into_inner())
}

/// Read and parse the manifest from a backup archive. For
/// encrypted backups the password is required (and acts as the
/// password verification — successful decryption is the proof).
pub fn read_backup_manifest(
    backup_path: &Path,
    password: Option<&str>,
) -> Result<BackupManifest, BackupError> {
    use std::io::Cursor;
    let inner = load_inner_zip(backup_path, password)?;
    manifest_of(&mut ZipArchive::new(Cursor::new(inner))?)
}

/// The parsed `manifest.json` of an open archive.
fn manifest_of<R: Read + std::io::Seek>(
    archive: &mut ZipArchive<R>,
) -> Result<BackupManifest, BackupError> {
    let mut manifest_file = archive.by_name("manifest.json")?;
    let mut manifest_content = String::new();
    manifest_file.read_to_string(&mut manifest_content)?;
    Ok(serde_json::from_str(&manifest_content)?)
}

/// Refuse an archive in another format.
fn check_format_version(manifest: &BackupManifest) -> Result<(), BackupError> {
    if manifest.backup_format_version != BACKUP_FORMAT_VERSION {
        return Err(BackupError::CorruptedBackup(format!(
            "unsupported backup format version {} (this build expects {})",
            manifest.backup_format_version, BACKUP_FORMAT_VERSION
        )));
    }
    Ok(())
}

/// Preview what a restore would do. Always decrypts when needed
/// (so a successful preview also proves the password works,
/// replacing the dropped `verify_backup_password` helper).
pub fn preview_restore(
    backup_path: &Path,
    password: Option<&str>,
) -> Result<RestorePreview, BackupError> {
    let encrypted = is_encrypted_backup(backup_path)?;
    let manifest = read_backup_manifest(backup_path, password)?;

    // A backup this build can't restore is refused here, before the
    // operator is asked to confirm anything.
    check_format_version(&manifest)?;
    let upgrade =
        match super::backup_upgrade::schema_point(&manifest).map_err(BackupError::NotRestorable)? {
            SchemaPoint::Current => None,
            SchemaPoint::Earlier { .. } => Some(RestoreUpgrade {
                from_version: manifest.nosdesk_version.clone(),
                to_version: env!("CARGO_PKG_VERSION").to_string(),
                replaced_tables: Vec::new(),
            }),
        };

    let mut warnings = Vec::new();

    if manifest.files.total_size_bytes > 1024 * 1024 * 1024 {
        warnings.push(format!(
            "Backup contains {} GB of files, restore may take a while",
            manifest.files.total_size_bytes / (1024 * 1024 * 1024)
        ));
    }

    Ok(RestorePreview {
        manifest,
        encrypted,
        upgrade,
        warnings,
    })
}

/// Restore files from a backup archive. For encrypted backups
/// True when `rel` is a plain relative path safe to join under the
/// uploads root: every component is a normal name (or `.`), with no
/// `..`, no absolute/root/prefix component, and no NUL/backslash. Used
/// as the zip-slip guard in [`restore_backup_files`].
fn is_safe_backup_relative_path(rel: &str) -> bool {
    use std::path::Component;
    if rel.is_empty() || rel.contains('\0') || rel.contains('\\') {
        return false;
    }
    Path::new(rel)
        .components()
        .all(|c| matches!(c, Component::Normal(_) | Component::CurDir))
}

/// the password is required to unwrap the outer envelope.
pub fn restore_backup_files(
    backup_path: &Path,
    password: Option<&str>,
) -> Result<u64, BackupError> {
    use std::io::Cursor;
    let inner = load_inner_zip(backup_path, password)?;
    let mut archive = ZipArchive::new(Cursor::new(inner))?;

    let uploads_dir = get_uploads_dir();
    let mut restored_count = 0u64;

    for i in 0..archive.len() {
        let mut file = archive.by_index(i)?;
        let name = file.name().to_string();

        if name.starts_with("files/") && !name.ends_with('/') {
            let relative_path = name.strip_prefix("files/").unwrap();

            // Zip-slip guard: a crafted backup with an entry like
            // `files/../../../etc/cron.d/x` (or an absolute path, which
            // would replace uploads_dir entirely in `join`) must not
            // escape the uploads root. Reject anything that isn't a
            // plain relative path before touching the filesystem. See
            // security-audit-2026-06.
            if !is_safe_backup_relative_path(relative_path) {
                log::warn!("restore: skipping backup file entry with unsafe path '{name}'");
                continue;
            }
            let dest_path = uploads_dir.join(relative_path);

            if let Some(parent) = dest_path.parent() {
                fs::create_dir_all(parent)?;
            }

            let mut dest_file = File::create(&dest_path)?;
            std::io::copy(&mut file, &mut dest_file)?;
            restored_count += 1;
        }
    }

    Ok(restored_count)
}

/// Delete a backup file
pub fn delete_backup_file(file_path: &str) -> Result<(), BackupError> {
    let path = Path::new(file_path);
    if path.exists() {
        fs::remove_file(path)?;
    }
    Ok(())
}

/// Stats from database restore.
#[derive(Debug, Default, serde::Serialize)]
pub struct RestoreStats {
    pub tables_restored: usize,
    pub records_restored: usize,
    /// Per-table breakdown so the operator can see exactly which
    /// rows landed where. With the single-transaction-on-abort
    /// flow this is always a complete picture (no partial
    /// commits), but it's still load-bearing for operator
    /// confidence after a successful restore.
    pub per_table: Vec<TableRestoreResult>,
}

#[derive(Debug, serde::Serialize)]
pub struct TableRestoreResult {
    pub table: String,
    pub rows_attempted: usize,
    pub rows_loaded: usize,
}

/// Knobs for [`restore_database`]. New options should default
/// to the safer behaviour so a caller that doesn't pass one
/// gets the locked-down path.
#[derive(Default, Clone)]
pub struct RestoreOptions {
    /// Bypass the empty-target-database precheck. The CLI
    /// exposes this as `--force`; the web handler sets it
    /// implicitly because admin-auth is the upstream gate.
    pub force_non_empty: bool,
    /// A connection URL for the server the restore runs on, as the role it
    /// runs as. A backup from an earlier version is upgraded in a scratch
    /// database created there; without a URL such a backup is refused.
    /// [`restore_instance`] fills it in.
    pub server_url: Option<String>,
    /// Row JSON per load statement; [`RESTORE_CHUNK_BYTES`] when unset.
    /// Tests set it small to exercise chunking without large fixtures.
    #[doc(hidden)]
    pub chunk_bytes: Option<usize>,
}

/// Leaves the URL out: it carries the role's password.
impl std::fmt::Debug for RestoreOptions {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("RestoreOptions")
            .field("force_non_empty", &self.force_non_empty)
            .field("server_url", &self.server_url.as_ref().map(|_| "<set>"))
            .field("chunk_bytes", &self.chunk_bytes)
            .finish()
    }
}

/// A connection as the role an instance restore runs as: the migration role
/// when `MIGRATION_DATABASE_URL` is set (an error when it can't be reached),
/// else `runtime`.
pub fn restore_connection(runtime: &crate::db::Pool) -> Result<DbConnection, BackupError> {
    let migration_role = crate::db::migration_role_pool().map_err(|e| {
        tracing::error!(error = %e, "restore: MIGRATION_DATABASE_URL is set but couldn't connect");
        BackupError::MigrationRoleUnreachable(e.to_string())
    })?;
    match migration_role {
        Some(pool) => pool.get(),
        None => runtime.get(),
    }
    .map_err(|e| {
        tracing::error!(error = %e, "restore: no database connection");
        BackupError::ConnectionUnavailable(e.to_string())
    })
}

/// Fill in which live tables an upgrade restore of `preview`'s backup
/// replaces (see [`tables_backup_predates`]). Best effort: the preview stands
/// without the list when the restore role can't be reached.
pub fn list_replaced_tables(runtime: &crate::db::Pool, preview: &mut RestorePreview) {
    let Some(upgrade) = preview.upgrade.as_mut() else {
        return;
    };
    let listed = restore_connection(runtime)
        .and_then(|mut conn| tables_backup_predates(&mut conn, &preview.manifest));
    match listed {
        Ok(tables) => upgrade.replaced_tables = tables,
        Err(e) => {
            tracing::warn!(error = %e, "restore preview: couldn't list the tables it replaces")
        }
    }
}

/// Restore an instance's database from a backup archive. The CLI and the
/// admin restore both come here, so neither picks the database role itself.
///
/// The restore truncates and reloads every table with triggers off
/// (`session_replication_role`), which needs a superuser role, not the app
/// role (`nosdesk_app`). It runs as the migration role when one is configured
/// (`MIGRATION_DATABASE_URL`), and fails if that role can't be reached rather
/// than falling back to `DATABASE_URL`, which would only fail later. Without
/// one it runs on `runtime`, as a single-role install's `DATABASE_URL` is a
/// superuser already. A backup from an earlier version is upgraded in a
/// scratch database created as the same role. Returns the connection it ran
/// on, for the work that follows (the thumbnail backfill).
pub fn restore_instance(
    runtime: &crate::db::Pool,
    backup_path: &Path,
    password: Option<&str>,
    mut options: RestoreOptions,
) -> Result<(RestoreStats, DbConnection), BackupError> {
    let mut conn = restore_connection(runtime)?;
    if options.server_url.is_none() {
        options.server_url = crate::db::migration_database_url();
    }
    let stats = restore_database(&mut conn, backup_path, password, options)?;
    Ok((stats, conn))
}

/// Session advisory lock a restore holds on the database it restores, so a
/// second restore (a double click, or a retry after a proxy timeout) is
/// refused rather than racing the first.
pub const RESTORE_LOCK_KEY: i64 = 0x6e6f_7364_7273_746f; // "nosdrsto"

/// Instance-wide tables a backup from an earlier version can predate.
/// Restoring such a backup leaves their live rows as they are rather than
/// clearing them: the backup has nothing to say about them.
const KEEP_LIVE_WHEN_PREDATED: &[&str] = &["instance_settings"];

/// Restore a backup archive into the database `conn` points at.
/// Outside tests, call [`restore_instance`], which picks the connection.
///
/// A backup from this build's schema loads as it is. One from an earlier
/// version (back to 1.0.0) is first upgraded: its rows load into a scratch
/// database at the schema they were taken at, the later migrations run over
/// them as an in-place upgrade would, and the result loads here
/// (`backup_upgrade`). A backup this build can't place is refused before
/// anything changes, and so is a second restore while one runs.
///
/// The load runs inside a single transaction with
/// `session_replication_role = 'replica'`, so:
///
///   - The whole restore is atomic. A FK violation on row #501
///     of a 1000-row table rolls back rows 1..500 of that table
///     and every prior table in the same call. The operator
///     never sees a half-restored database.
///   - FK ordering between tables is a non-issue: the trigger
///     suspension covers FK + user triggers but not UNIQUE /
///     CHECK constraints, so structurally-bad rows still fail.
///   - The restore order comes from `discover_user_tables`
///     against the live schema, intersected with what's in the
///     backup. Tables that exist live but aren't in the backup
///     are left as they are.
///
/// Pre-flight: refuses on a non-empty users table unless the
/// caller sets `options.force_non_empty`. The CLI exposes this
/// as `--force`; the web admin endpoint sets it implicitly.
pub fn restore_database(
    conn: &mut DbConnection,
    backup_path: &Path,
    password: Option<&str>,
    options: RestoreOptions,
) -> Result<RestoreStats, BackupError> {
    use diesel::prelude::*;
    use diesel::sql_query;
    use diesel::sql_types::BigInt;

    #[derive(QueryableByName)]
    struct Locked {
        #[diesel(sql_type = diesel::sql_types::Bool)]
        locked: bool,
    }
    let locked: Locked = sql_query("SELECT pg_try_advisory_lock($1) AS locked")
        .bind::<BigInt, _>(RESTORE_LOCK_KEY)
        .get_result(conn)
        .map_err(BackupError::DatabaseError)?;
    if !locked.locked {
        return Err(BackupError::RestoreInProgress);
    }
    // The connection goes back to a pool, so the lock is released however
    // the restore ends, a panic included; a lock left on it would refuse
    // every later restore.
    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        restore_database_locked(conn, backup_path, password, options)
    }));
    if let Err(e) = sql_query("SELECT pg_advisory_unlock($1)")
        .bind::<BigInt, _>(RESTORE_LOCK_KEY)
        .execute(conn)
    {
        tracing::warn!(error = %e, "restore: couldn't release the restore lock; it ends with the session");
    }
    match result {
        Ok(Ok(stats)) => {
            tracing::info!(count = stats.records_restored, "restore: finished");
            Ok(stats)
        }
        Ok(Err(e)) => {
            tracing::warn!(error = %e, "restore: failed; the database is as it was");
            Err(e)
        }
        Err(panic) => std::panic::resume_unwind(panic),
    }
}

/// [`restore_database`], holding the restore lock.
fn restore_database_locked(
    conn: &mut DbConnection,
    backup_path: &Path,
    password: Option<&str>,
    options: RestoreOptions,
) -> Result<RestoreStats, BackupError> {
    use diesel::deserialize::QueryableByName;
    use diesel::prelude::*;
    use diesel::sql_query;
    use diesel::sql_types::BigInt;
    use std::io::Cursor;

    // Scratch databases a killed restore left behind. Nothing else uses them
    // while this restore holds the lock.
    super::backup_upgrade::drop_leftover_scratch_databases(conn);

    // ---- Load the inner zip (decrypts if encrypted) and place it ----
    let inner_zip = load_inner_zip(backup_path, password)?;
    let manifest = manifest_of(&mut ZipArchive::new(Cursor::new(&inner_zip[..]))?)?;
    check_format_version(&manifest)?;
    let point =
        super::backup_upgrade::schema_point(&manifest).map_err(BackupError::NotRestorable)?;
    if let SchemaPoint::Earlier { .. } = point {
        if options.server_url.is_none() {
            return Err(BackupError::UpgradeFailed(
                "no database URL to create the upgrade database with".to_string(),
            ));
        }
        super::backup_upgrade::require_upgrade_privileges(conn)?;
    }

    // ---- Pre-flight empty-target check ----
    if !options.force_non_empty {
        #[derive(QueryableByName)]
        struct CountRow {
            #[diesel(sql_type = BigInt)]
            n: i64,
        }
        let count: CountRow = sql_query("SELECT COUNT(*)::bigint AS n FROM users")
            .get_result(conn)
            .map_err(BackupError::DatabaseError)?;
        if count.n > 0 {
            return Err(BackupError::CorruptedBackup(format!(
                "target database is not empty ({} existing users); pass --force to overwrite",
                count.n
            )));
        }
    }

    let chunk_bytes = options.chunk_bytes.unwrap_or(RESTORE_CHUNK_BYTES);
    let (rows, keep_live, into) = match point {
        SchemaPoint::Current => (inner_zip, Vec::new(), LoadInto::Live),
        SchemaPoint::Earlier { migration } => {
            let server_url = options
                .server_url
                .as_deref()
                .expect("checked above for an earlier backup");
            tracing::info!(
                backup_from_version = %manifest.nosdesk_version,
                backup_migration = migration,
                "restore: upgrading a backup from an earlier version"
            );
            let upgraded = super::backup_upgrade::upgrade_archive(
                conn,
                server_url,
                &inner_zip,
                migration,
                chunk_bytes,
            )?;
            let upgraded_manifest = manifest_of(&mut ZipArchive::new(Cursor::new(&upgraded[..]))?)?;
            // A table the backup predates comes out of the upgrade empty;
            // an instance-wide one keeps its live rows instead.
            let keep_live = KEEP_LIVE_WHEN_PREDATED
                .iter()
                .filter(|t| !manifest.tables.contains_key(**t))
                .filter(|t| {
                    upgraded_manifest
                        .tables
                        .get(**t)
                        .is_none_or(|m| m.count == 0)
                })
                .map(|t| t.to_string())
                .collect();
            (upgraded, keep_live, LoadInto::LiveUpgraded)
        }
    };
    load_archive(conn, &rows, into, &keep_live, chunk_bytes)
}

/// Tables in this database that `manifest`'s backup predates and that hold
/// rows now: restoring it replaces them with what the upgrade produces,
/// which for settings means their defaults. Instance-wide tables the restore
/// keeps are left out. Needs a connection that sees every row.
pub fn tables_backup_predates(
    conn: &mut DbConnection,
    manifest: &BackupManifest,
) -> Result<Vec<String>, BackupError> {
    use diesel::prelude::*;
    use diesel::sql_query;
    use diesel::sql_types::Bool;

    #[derive(QueryableByName)]
    struct HasRows {
        #[diesel(sql_type = Bool)]
        has_rows: bool,
    }
    let mut predated = Vec::new();
    for table in discover_user_tables(conn)? {
        if manifest.tables.contains_key(&table) || KEEP_LIVE_WHEN_PREDATED.contains(&table.as_str())
        {
            continue;
        }
        // `table` came from the catalogue; quote it all the same.
        let row: HasRows = sql_query(format!(
            "SELECT EXISTS (SELECT 1 FROM public.\"{}\") AS has_rows",
            table.replace('"', "\"\"")
        ))
        .get_result(conn)
        .map_err(BackupError::DatabaseError)?;
        if row.has_rows {
            predated.push(table);
        }
    }
    Ok(predated)
}

/// Which database [`load_archive`] fills.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum LoadInto {
    /// The live database, at this build's schema.
    Live,
    /// The live database, with the rows of an upgraded older backup.
    LiveUpgraded,
    /// A scratch database at an older backup's own schema, to be migrated.
    Scratch,
}

/// Replace the tables of the database `conn` points at with the rows of
/// `inner_zip`, an archive at that database's schema, in one transaction.
/// Tables in `keep` are left as they are.
pub(crate) fn load_archive(
    conn: &mut DbConnection,
    inner_zip: &[u8],
    into: LoadInto,
    keep: &[String],
    chunk_bytes: usize,
) -> Result<RestoreStats, BackupError> {
    use diesel::connection::Connection;
    use diesel::prelude::*;
    use diesel::sql_query;
    use std::io::Cursor;

    let mut archive = ZipArchive::new(Cursor::new(inner_zip))?;
    let manifest = manifest_of(&mut archive)?;

    // ---- Figure out what to restore ----
    let live_tables: std::collections::HashSet<String> =
        discover_user_tables(conn)?.into_iter().collect();
    // Skip partition children if a backup carries them; the
    // parent's rows route to the right child on insert.
    let partition_children = partition_children(conn)?;
    let mut backup_tables: Vec<String> = manifest.tables.keys().cloned().collect();
    backup_tables.sort();

    let mut skipped_unknown: Vec<String> = Vec::new();
    let mut skipped_partition: Vec<String> = Vec::new();
    let restore_order: Vec<String> = backup_tables
        .into_iter()
        .filter(|t| {
            if keep.contains(t) {
                return false;
            }
            if partition_children.contains(t) {
                skipped_partition.push(t.clone());
                return false;
            }
            if live_tables.contains(t) {
                true
            } else {
                skipped_unknown.push(t.clone());
                false
            }
        })
        .collect();
    for name in &skipped_unknown {
        log::warn!("restore: skipping table '{name}' that is in the backup but not in the schema");
    }
    for name in &skipped_partition {
        log::info!(
            "restore: skipping partition child '{name}'; parent table covers its rows on restore"
        );
    }

    // ---- Load + hash-check every table BEFORE the
    //      transaction. The payload stays as raw JSON
    //      text and is bound to the restore INSERT
    //      server-side; routing it through
    //      `serde_json::Value` here would coerce numbers
    //      into f64 and lose NUMERIC precision (a JSONB
    //      column holding 10.000 would come back 10.0).
    let mut table_payloads: Vec<(String, String, usize)> = Vec::with_capacity(restore_order.len());
    for table_name in &restore_order {
        let data_path = format!("data/{table_name}.json");
        let content = match archive.by_name(&data_path) {
            Ok(mut data_file) => {
                let mut buf = String::new();
                data_file.read_to_string(&mut buf)?;
                buf
            }
            Err(_) => continue,
        };

        let expected = &manifest
            .tables
            .get(table_name)
            .expect("table present in restore_order is in manifest by construction")
            .sha256;
        let actual = sha256_hex(content.as_bytes());
        if &actual != expected {
            return Err(BackupError::CorruptedBackup(format!(
                "sha256 mismatch for table '{table_name}': manifest={expected} computed={actual}"
            )));
        }

        let row_count = manifest
            .tables
            .get(table_name)
            .map(|m| m.count as usize)
            .unwrap_or(0);
        table_payloads.push((table_name.clone(), content, row_count));
    }

    // ---- Single transaction with FK + trigger
    //      suppression. First row failure rolls back
    //      the entire restore.
    conn.transaction::<RestoreStats, BackupError, _>(|c| {
        sql_query("SET LOCAL session_replication_role = 'replica'")
            .execute(c)
            .map_err(BackupError::DatabaseError)?;

        // Clear migration-seeded rows from the tables we're
        // about to restore so explicit IDs in the backup don't
        // collide.
        if !table_payloads.is_empty() {
            let names: Vec<String> = table_payloads
                .iter()
                .map(|(n, _, _)| format!("\"{}\"", n.replace('"', "\"\"")))
                .collect();
            let stmt = format!(
                "TRUNCATE TABLE {} RESTART IDENTITY CASCADE",
                names.join(", ")
            );
            sql_query(&stmt)
                .execute(c)
                .map_err(BackupError::DatabaseError)?;
        }

        let mut stats = RestoreStats::default();

        for (table_name, payload, rows_attempted) in &table_payloads {
            if *rows_attempted == 0 {
                stats.per_table.push(TableRestoreResult {
                    table: table_name.clone(),
                    rows_attempted: 0,
                    rows_loaded: 0,
                });
                continue;
            }
            let rows_loaded = restore_table_data_in_chunks(c, table_name, payload, chunk_bytes)?;
            if rows_loaded > 0 {
                stats.tables_restored += 1;
                stats.records_restored += rows_loaded;
            }
            stats.per_table.push(TableRestoreResult {
                table: table_name.clone(),
                rows_attempted: *rows_attempted,
                rows_loaded,
            });
        }

        // setval is transactional in PG 18; rollback unwinds it.
        reset_sequences(c)?;
        // Ticket numbers come from per-workspace sequences that the reset above
        // doesn't see; the rows arrived with their numbers while triggers were
        // off, so move each workspace's sequence past its highest. A scratch
        // database at an older schema may predate them; its migrations number
        // the tickets, and the live load that follows runs this.
        if into != LoadInto::Scratch {
            sql_query("SELECT public.sync_ticket_number_sequences()")
                .execute(c)
                .map_err(BackupError::DatabaseError)?;
        }
        if into == LoadInto::LiveUpgraded {
            // The rows carry the schema fingerprint of the server that made
            // the backup; this server's is the one that holds now.
            crate::sync::system_meta::set_schema_hash(c, SERVER_SCHEMA_HASH)
                .map_err(BackupError::DatabaseError)?;
        }
        Ok(stats)
    })
}

/// Re-align every column-owned sequence to MAX(col)+1. Sourced
/// from `pg_depend` so any serial / bigserial / identity column
/// is covered without a hand-maintained list.
fn reset_sequences(conn: &mut DbConnection) -> Result<(), BackupError> {
    use diesel::deserialize::QueryableByName;
    use diesel::prelude::*;
    use diesel::sql_query;
    use diesel::sql_types::Text;

    #[derive(QueryableByName)]
    struct SequenceOwner {
        #[diesel(sql_type = Text)]
        seq_qualified: String,
        #[diesel(sql_type = Text)]
        table_qualified: String,
        #[diesel(sql_type = Text)]
        column_name: String,
    }

    // Resolve every sequence that's `OWNED BY` a column. The
    // serial / bigserial / identity machinery all wire through
    // pg_depend with deptype='a' (auto). Restricted to public
    // schema and to numeric columns so the setval cast below
    // is safe.
    let owners: Vec<SequenceOwner> = sql_query(
        "SELECT \
             format('%I.%I', n.nspname, c.relname) AS seq_qualified, \
             format('%I.%I', tn.nspname, t.relname) AS table_qualified, \
             a.attname AS column_name \
         FROM pg_class c \
         JOIN pg_namespace n ON n.oid = c.relnamespace \
         JOIN pg_depend d \
           ON d.objid = c.oid \
          AND d.classid = 'pg_class'::regclass \
          AND d.refclassid = 'pg_class'::regclass \
          AND d.deptype = 'a' \
         JOIN pg_class t ON t.oid = d.refobjid \
         JOIN pg_namespace tn ON tn.oid = t.relnamespace \
         JOIN pg_attribute a \
           ON a.attrelid = t.oid \
          AND a.attnum = d.refobjsubid \
         WHERE c.relkind = 'S' \
           AND n.nspname = 'public' \
           AND tn.nspname = 'public'",
    )
    .load(conn)
    .map_err(BackupError::DatabaseError)?;

    for SequenceOwner {
        seq_qualified,
        table_qualified,
        column_name,
    } in owners
    {
        let stmt = format!(
            "SELECT setval('{seq_qualified}', COALESCE((SELECT MAX(\"{column_name}\") FROM {table_qualified}), 0) + 1, false)"
        );
        if let Err(e) = sql_query(&stmt).execute(conn) {
            log::warn!(
                "reset_sequences: failed to reset {seq_qualified} (owner {table_qualified}.{column_name}): {e}"
            );
        }
    }

    log::info!("reset_sequences: aligned all owned sequences to MAX+1");
    Ok(())
}

/// Restore one table's rows. The JSON array payload travels as
/// raw text and is cast to jsonb server-side via `$1::jsonb` so
/// Postgres's own JSON parser handles numeric values
/// (NUMERIC(12,3) → "10.000" stays "10.000"). Round-tripping
/// through `serde_json::Value` would coerce numbers into f64
/// and lose precision.
///
/// `jsonb_populate_recordset(NULL::table, ...)` then runs the
/// per-column conversion against the target record type. Extra
/// JSON keys are ignored; missing keys default to NULL, except a
/// column in `MISSING_COLUMNS`.
#[cfg(test)]
fn restore_table_data(
    conn: &mut DbConnection,
    table_name: &str,
    payload: &str,
) -> Result<usize, BackupError> {
    restore_table_data_in_chunks(conn, table_name, payload, RESTORE_CHUNK_BYTES)
}

/// How much row JSON one restore statement carries. Postgres caps a jsonb
/// array at 256 MB, so a large table loads in several statements, all in
/// the restore's one transaction.
pub(crate) const RESTORE_CHUNK_BYTES: usize = 32 * 1024 * 1024;

/// [`restore_table_data`], loading at most about `chunk_bytes` of row JSON
/// per statement (always at least one row).
fn restore_table_data_in_chunks(
    conn: &mut DbConnection,
    table_name: &str,
    payload: &str,
    chunk_bytes: usize,
) -> Result<usize, BackupError> {
    if payload.len() <= chunk_bytes {
        return restore_rows(conn, table_name, payload);
    }
    // Split without parsing values: `RawValue` keeps each row's text as it
    // is, so numbers keep their precision.
    let rows: Vec<&serde_json::value::RawValue> = serde_json::from_str(payload)?;
    let mut loaded = 0;
    let mut chunk = String::from("[");
    for row in rows {
        let text = row.get();
        if chunk.len() > 1 && chunk.len() + text.len() + 2 > chunk_bytes {
            chunk.push(']');
            loaded += restore_rows(conn, table_name, &chunk)?;
            chunk.clear();
            chunk.push('[');
        }
        if chunk.len() > 1 {
            chunk.push(',');
        }
        chunk.push_str(text);
    }
    if chunk.len() > 1 {
        chunk.push(']');
        loaded += restore_rows(conn, table_name, &chunk)?;
    }
    Ok(loaded)
}

/// Load one JSON array of `table_name` rows.
fn restore_rows(
    conn: &mut DbConnection,
    table_name: &str,
    payload: &str,
) -> Result<usize, BackupError> {
    use diesel::prelude::*;
    use diesel::sql_query;
    use diesel::sql_types::Text;

    if !table_exists_in_db(conn, table_name)? {
        return Err(BackupError::CorruptedBackup(format!(
            "backup references unknown table '{table_name}'"
        )));
    }
    if payload.is_empty() || payload.trim() == "[]" {
        return Ok(0);
    }

    if !table_name
        .chars()
        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
    {
        return Err(BackupError::CorruptedBackup(format!(
            "unsafe table identifier '{table_name}'"
        )));
    }

    let stmt = format!(
        "INSERT INTO public.{table_name} \
         SELECT * FROM jsonb_populate_recordset(NULL::public.{table_name}, {rows})",
        rows = payload_rows(table_name),
    );
    let count = sql_query(&stmt)
        .bind::<Text, _>(payload)
        .execute(conn)
        .map_err(|e| {
            BackupError::DatabaseError(diesel::result::Error::QueryBuilderError(
                format!("table '{table_name}' restore failed: {e}").into(),
            ))
        })?;
    Ok(count)
}

/// A column a password-less backup leaves out (`SENSITIVE_FIELDS`) that the
/// table can't load without. Only sensitive fields belong here: a backup
/// from an earlier schema is migrated, not patched (`backup_upgrade`).
struct MissingColumn {
    table: &'static str,
    column: &'static str,
    /// The row to load instead, as SQL over the backup row `r`; `None`
    /// skips the row.
    load: Option<&'static str>,
}

const MISSING_COLUMNS: &[MissingColumn] = &[
    // Tokens and recovery codes are nothing without their hashes.
    MissingColumn {
        table: "refresh_tokens",
        column: "token_hash",
        load: None,
    },
    MissingColumn {
        table: "reset_tokens",
        column: "token_hash",
        load: None,
    },
    MissingColumn {
        table: "api_tokens",
        column: "token_hash",
        load: None,
    },
    MissingColumn {
        table: "user_recovery_codes",
        column: "code_hash",
        load: None,
    },
    // A webhook gets a new secret, and stays off until an admin gives the
    // receiver the new one.
    MissingColumn {
        table: "webhooks",
        column: "secret",
        load: Some(
            "r || jsonb_build_object('secret', 'whsec_' || encode(public.gen_random_bytes(32), 'hex'), 'enabled', false)",
        ),
    },
    // No MFA secret means no MFA (and no key id for it): staff are asked to
    // set it up again.
    MissingColumn {
        table: "users",
        column: "mfa_secret",
        load: Some("r || jsonb_build_object('mfa_enabled', false, 'mfa_secret_kek_id', NULL)"),
    },
];

/// The `$1` payload as the rows to load, with `MISSING_COLUMNS` applied.
fn payload_rows(table_name: &str) -> String {
    let Some(missing) = MISSING_COLUMNS.iter().find(|m| m.table == table_name) else {
        return "$1::jsonb".to_owned();
    };
    let column = missing.column;
    let (row, keep) = match missing.load {
        Some(load) => (
            format!("CASE WHEN r ? '{column}' THEN r ELSE {load} END"),
            "true".to_owned(),
        ),
        None => ("r".to_owned(), format!("r ? '{column}'")),
    };
    format!(
        "(SELECT coalesce(jsonb_agg({row}), '[]'::jsonb) \
         FROM jsonb_array_elements($1::jsonb) r WHERE {keep})"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── zip-slip guard ───────────────────────────────────────────

    #[test]
    fn backup_relative_path_guard_blocks_traversal_and_absolute() {
        assert!(is_safe_backup_relative_path("avatars/u1.png"));
        assert!(is_safe_backup_relative_path("a/b/c.bin"));
        // Traversal and absolute paths must be rejected (the latter
        // would replace uploads_dir in PathBuf::join).
        assert!(!is_safe_backup_relative_path("../../etc/passwd"));
        assert!(!is_safe_backup_relative_path("a/../../b"));
        assert!(!is_safe_backup_relative_path("/etc/passwd"));
        assert!(!is_safe_backup_relative_path("a\\b"));
        assert!(!is_safe_backup_relative_path(""));
    }

    // ── derive_key ───────────────────────────────────────────────

    #[test]
    fn derive_key_produces_32_bytes() {
        let key = derive_key("password", b"saltsaltsaltsalt");
        assert_eq!(key.len(), 32);
    }

    #[test]
    fn derive_key_is_deterministic() {
        let salt = b"fixed-salt-value-for-test1234567";
        let k1 = derive_key("pass", salt);
        let k2 = derive_key("pass", salt);
        assert_eq!(k1, k2);
    }

    #[test]
    fn derive_key_differs_for_different_passwords() {
        let salt = b"fixed-salt-value-for-test1234567";
        let k1 = derive_key("password1", salt);
        let k2 = derive_key("password2", salt);
        assert_ne!(k1, k2);
    }

    // ── encrypt_data / decrypt_data roundtrip ────────────────────

    #[test]
    fn encrypt_decrypt_roundtrip() {
        let key = derive_key("test-password", b"salt-for-encrypt-decrypt-test!!");
        let plaintext = b"hello world, this is secret data";
        let (ciphertext, nonce) = encrypt_data(plaintext, &key).unwrap();
        assert_ne!(&ciphertext[..plaintext.len()], plaintext);

        let decrypted = decrypt_data(&ciphertext, &key, &nonce).unwrap();
        assert_eq!(decrypted, plaintext);
    }

    #[test]
    fn decrypt_with_wrong_key_fails() {
        let key = derive_key("correct", b"salt-for-wrong-key-test!!!!!!!!");
        let wrong_key = derive_key("wrong", b"salt-for-wrong-key-test!!!!!!!!");
        let (ciphertext, nonce) = encrypt_data(b"secret", &key).unwrap();
        assert!(decrypt_data(&ciphertext, &wrong_key, &nonce).is_err());
    }

    // ── table allowlist (AUD-008, post-introspection rewrite) ────

    #[test]
    fn table_exists_in_db_accepts_real_tables() {
        use crate::test_helpers::setup_test_connection;
        let mut conn = setup_test_connection();
        // `users` is the load-bearing table that the rest of the
        // system depends on; if it's missing from the test DB
        // we've got bigger problems than this test.
        assert!(table_exists_in_db(&mut conn, "users").unwrap());
        assert!(table_exists_in_db(&mut conn, "tickets").unwrap());
    }

    #[test]
    fn table_exists_in_db_rejects_unknown_or_hostile_names() {
        use crate::test_helpers::setup_test_connection;
        let mut conn = setup_test_connection();
        for hostile in [
            "",
            "pg_authid", // exists in pg_catalog, not public
            "users; DROP TABLE users; --",
            "users) RETURNING *; --",
            "USERS", // case-sensitive in PG; public.users is lowercase
            "Users",
            "schema.users",
            "secret_table",
            "__diesel_schema_migrations", // in EXCLUDE list at discover time, but still exists; the test guards the WRONG-table path
        ] {
            if hostile == "__diesel_schema_migrations" {
                // The exclude list is enforced at *discover* time
                // (so we don't BACK UP it), not at *exists* time
                // (it's a real table in the DB). Skip this one;
                // it would pass `table_exists_in_db` correctly.
                continue;
            }
            assert!(
                !table_exists_in_db(&mut conn, hostile).unwrap(),
                "expected rejection for {hostile:?}"
            );
        }
    }

    #[test]
    fn discover_user_tables_excludes_diesel_migrations() {
        use crate::test_helpers::setup_test_connection;
        let mut conn = setup_test_connection();
        let tables = discover_user_tables(&mut conn).unwrap();
        assert!(!tables.iter().any(|t| t == "__diesel_schema_migrations"));
        // Sanity: discovers core user tables.
        assert!(tables.iter().any(|t| t == "users"));
        assert!(tables.iter().any(|t| t == "tickets"));
        // The bug that started this rewrite: channels table must
        // now be discovered automatically.
        assert!(
            tables.iter().any(|t| t == "channels"),
            "channels table must be in the backup discovery (this is the AUD-014 regression guard)"
        );
    }

    // ── DB-backed: poisoned-backup defence (AUD-008) ─────────────

    #[test]
    fn restore_table_data_ignores_hostile_column_names() {
        // A poisoned backup might ship a row whose JSON keys carry
        // SQL fragments instead of real column names. With the
        // pre-AUD-008 string-concatenation pattern this would have
        // landed straight in the INSERT statement. With
        // jsonb_populate_record, unknown keys are silently dropped
        // and Postgres treats them as no-ops. This test confirms:
        // (a) the legitimate column data is restored intact, and
        // (b) the hostile keys aren't executed (the users table
        //     still exists, no extra rows appear, etc).
        use crate::test_helpers::setup_test_connection;
        use diesel::prelude::*;
        use uuid::Uuid;

        let mut conn = setup_test_connection();

        let uuid = Uuid::new_v4();
        // Full row shape, matching what a real backup would
        // capture. `jsonb_populate_recordset` writes NULL for
        // missing keys, so the JSON must spell out the NOT NULL
        // columns explicitly. The hostile keys at the end are
        // what we're actually testing.
        let row = serde_json::json!({
            "uuid": uuid,
            "name": "Restored Alice",
            "platform_role": "user",
            "feature_flag_overrides": {},
            "mfa_enabled": false,
            "created_at": "2026-01-01T00:00:00",
            "updated_at": "2026-01-01T00:00:00",
            "name); DROP TABLE users; --": "ignored",
            "id, mfa_enabled) VALUES (1,true": 42,
            "); SELECT pg_sleep(60)--": null,
        });

        let payload = serde_json::to_string(&[row]).expect("serialize row");
        let inserted = restore_table_data(&mut conn, "users", &payload)
            .expect("restore_table_data should not fail");
        assert_eq!(inserted, 1, "exactly one row inserted");

        // The legit row landed with the right name.
        let name: String = crate::schema::users::table
            .filter(crate::schema::users::uuid.eq(uuid))
            .select(crate::schema::users::name)
            .first(&mut conn)
            .expect("inserted user should be readable");
        assert_eq!(name, "Restored Alice");

        // The hostile-named columns weren't created; the users table
        // shape is whatever the schema says. A simple count query
        // succeeding confirms the table wasn't dropped or mutated.
        let count: i64 = crate::schema::users::table
            .count()
            .get_result(&mut conn)
            .expect("users table should still be queryable");
        assert!(count >= 1, "users table intact after hostile insert");
    }

    /// A password-less backup restores: every sensitive column it leaves out
    /// that the schema requires has a rule, and the rules cover nothing else.
    #[test]
    fn every_required_sensitive_column_has_a_restore_rule() {
        use crate::test_helpers::setup_test_connection;
        use diesel::sql_query;
        use diesel::sql_types::Text;

        #[derive(QueryableByName)]
        struct Nullable {
            #[diesel(sql_type = Text)]
            is_nullable: String,
        }

        let mut conn = setup_test_connection();
        for (table, columns) in SENSITIVE_FIELDS {
            for column in *columns {
                let row: Nullable = sql_query(
                    "SELECT is_nullable::text AS is_nullable FROM information_schema.columns \
                     WHERE table_schema = 'public' AND table_name = $1 AND column_name = $2",
                )
                .bind::<Text, _>(*table)
                .bind::<Text, _>(*column)
                .get_result(&mut conn)
                .unwrap_or_else(|e| panic!("{table}.{column} is in the schema: {e}"));
                if row.is_nullable == "NO" {
                    assert!(
                        MISSING_COLUMNS
                            .iter()
                            .any(|m| m.table == *table && m.column == *column),
                        "{table}.{column} is NOT NULL and stripped from plaintext backups, \
                         so it needs a MISSING_COLUMNS rule"
                    );
                }
            }
        }
        for rule in MISSING_COLUMNS {
            assert!(
                SENSITIVE_FIELDS
                    .iter()
                    .any(|(t, cs)| *t == rule.table && cs.contains(&rule.column)),
                "{}.{} isn't a sensitive field; an older schema is migrated, not patched",
                rule.table,
                rule.column
            );
        }
    }
}
