use chrono::Utc;
use diesel::prelude::*;
use ring::aead::{Aad, LessSafeKey, Nonce, UnboundKey, AES_256_GCM, NONCE_LEN};
use ring::pbkdf2;
use ring::rand::{SecureRandom, SystemRandom};
use std::collections::HashMap;
use std::fs::{self, File};
use std::io::{Read, Write};
use std::path::{Path, PathBuf};
use uuid::Uuid;
use walkdir::WalkDir;
use zip::write::FileOptions;
use zip::{ZipArchive, ZipWriter};

use crate::db::DbConnection;
use crate::models::{
    BackupJobUpdate, BackupManifest, FilesManifest, RestorePreview, TableManifest,
};
use crate::repository::backup as backup_repo;

// Encryption constants. AES-256-GCM + PBKDF2-HMAC-SHA256 are the
// same primitives the MFA encryption path uses; reusing them keeps
// the crypto surface area small.
const SALT_LENGTH: usize = 32;
const PBKDF2_ITERATIONS: u32 = 100_000;

/// Outer wrapper magic — 4 bytes prepended to encrypted backups so
/// the reader can tell at a glance whether to decrypt before
/// parsing. A plaintext backup IS a zip (starts with `PK\x03\x04`)
/// and skips this wrapper entirely.
const ENCRYPTED_MAGIC: &[u8; 4] = b"NODB";

/// Outer wrapper header: 4 magic + 4 format-version + 32 salt + 12 nonce.
const ENCRYPTED_HEADER_LEN: usize = 4 + 4 + SALT_LENGTH + NONCE_LEN;

/// Current on-disk backup format. Bumped only on breaking changes
/// to the wire shape (manifest schema, encryption envelope, etc.).
/// Pre-launch we start at 1; the field exists so future bumps can
/// refuse archives they can't parse.
const BACKUP_FORMAT_VERSION: u32 = 1;

/// Server schema hash baked in at compile time from the migrations
/// directory (see `build.rs`). Restore refuses backups whose
/// `schema_hash` doesn't match this value unless the operator
/// passes `--ignore-schema-mismatch`.
const SERVER_SCHEMA_HASH: &str = env!("NOSDESK_SCHEMA_HASH");

/// Fields that contain authentication material. Stripped from
/// plaintext (no-password) backups so a leaked zip can't be used
/// to recover credentials. Encrypted backups include them
/// normally — the whole archive is sealed by AES-GCM, so a
/// sidecar would just add complexity for no gain.
const SENSITIVE_FIELDS: &[(&str, &[&str])] = &[
    ("users", &["mfa_secret", "mfa_backup_codes"]),
    ("user_auth_identities", &["password_hash", "metadata"]),
    ("refresh_tokens", &["token_hash"]),
    ("reset_tokens", &["token_hash", "metadata"]),
];

/// Tables to export in backup
/// Tables to skip during backup discovery.
///
/// The list is exhaustive (and tested below) — every other
/// public-schema base table in the running DB ends up in the
/// backup, including any tables added by future migrations. This
/// is the Discourse / Supabase pattern: enumerate from
/// `information_schema`, then subtract the small set of tables
/// that are genuinely derivable from the running system rather
/// than from operator data.
///
/// Specifically NOT excluded (despite being tempting):
///   - `outbound_emails`: in-flight queue rows are user-relevant.
///     A backup taken mid-failure should retain queued retries.
///   - `webhook_deliveries`: same reasoning.
///   - `sync_actions`: the trigger-driven outbox. Empty most of
///     the time, but a backup-mid-burst can legitimately carry
///     in-flight events; the consumer worker is idempotent.
const EXCLUDE_FROM_BACKUP: &[&str] = &[
    // Diesel's own migration ledger. Regenerated by
    // `diesel migration run` on restore; including it would
    // re-run no-op migrations and possibly conflict on a server
    // that's already a step ahead.
    "__diesel_schema_migrations",
];

/// Discover the set of tables to back up by introspecting
/// `information_schema.tables`. Replaces the previous hardcoded
/// `BACKUP_TABLES` const that silently dropped any table added by
/// a migration but not added to the list (the AUD-014 bug class:
/// channels, outbound_emails, email_bounces all missed). Result
/// is sorted alphabetically for stable backup output across runs.
fn discover_user_tables(conn: &mut DbConnection) -> Result<Vec<String>, BackupError> {
    use diesel::deserialize::QueryableByName;
    use diesel::prelude::*;
    use diesel::sql_query;
    use diesel::sql_types::Text;

    #[derive(QueryableByName)]
    struct TableName {
        #[diesel(sql_type = Text)]
        table_name: String,
    }

    // Ordinary tables and partitioned parents only. Partition
    // children are excluded; the parent's row set covers them
    // and dumping both duplicates the data.
    let rows: Vec<TableName> = sql_query(
        "SELECT c.relname AS table_name \
         FROM pg_class c \
         JOIN pg_namespace n ON n.oid = c.relnamespace \
         WHERE n.nspname = 'public' \
           AND c.relkind IN ('r','p') \
           AND c.relispartition = false \
         ORDER BY c.relname",
    )
    .load(conn)
    .map_err(BackupError::DatabaseError)?;

    Ok(rows
        .into_iter()
        .map(|r| r.table_name)
        .filter(|t| !EXCLUDE_FROM_BACKUP.contains(&t.as_str()))
        .collect())
}

/// Names of partition-child tables in the public schema. The
/// restore path skips these because their rows arrive via the
/// parent table's payload.
fn partition_children(
    conn: &mut DbConnection,
) -> Result<std::collections::HashSet<String>, BackupError> {
    use diesel::deserialize::QueryableByName;
    use diesel::prelude::*;
    use diesel::sql_query;
    use diesel::sql_types::Text;

    #[derive(QueryableByName)]
    struct TableName {
        #[diesel(sql_type = Text)]
        table_name: String,
    }

    let rows: Vec<TableName> = sql_query(
        "SELECT c.relname AS table_name \
         FROM pg_class c \
         JOIN pg_namespace n ON n.oid = c.relnamespace \
         WHERE n.nspname = 'public' \
           AND c.relkind = 'r' \
           AND c.relispartition = true",
    )
    .load(conn)
    .map_err(BackupError::DatabaseError)?;

    Ok(rows.into_iter().map(|r| r.table_name).collect())
}

/// Defence-in-depth check used by `export_table_data` and the
/// restore path. Returns true only for tables actually present
/// in `information_schema.tables` for the public schema, so a
/// poisoned backup file (or a future caller bug) can't trick
/// the writer into interpolating an arbitrary identifier into
/// SQL.
fn table_exists_in_db(conn: &mut DbConnection, table_name: &str) -> Result<bool, BackupError> {
    use diesel::deserialize::QueryableByName;
    use diesel::prelude::*;
    use diesel::sql_query;
    use diesel::sql_types::{Bool, Text};

    #[derive(QueryableByName)]
    struct ExistsRow {
        #[diesel(sql_type = Bool)]
        exists: bool,
    }

    let row: ExistsRow = sql_query(
        "SELECT EXISTS ( \
            SELECT 1 FROM information_schema.tables \
            WHERE table_schema = 'public' \
              AND table_type = 'BASE TABLE' \
              AND table_name = $1 \
        ) AS exists",
    )
    .bind::<Text, _>(table_name)
    .get_result(conn)
    .map_err(BackupError::DatabaseError)?;
    Ok(row.exists)
}

/// Error type for backup operations
#[derive(Debug)]
pub enum BackupError {
    IoError(std::io::Error),
    ZipError(zip::result::ZipError),
    JsonError(serde_json::Error),
    DatabaseError(diesel::result::Error),
    EncryptionError(String),
    InvalidPassword,
    CorruptedBackup(String),
}

impl std::fmt::Display for BackupError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            BackupError::IoError(e) => write!(f, "IO error: {e}"),
            BackupError::ZipError(e) => write!(f, "ZIP error: {e}"),
            BackupError::JsonError(e) => write!(f, "JSON error: {e}"),
            BackupError::DatabaseError(e) => write!(f, "Database error: {e}"),
            BackupError::EncryptionError(e) => write!(f, "Encryption error: {e}"),
            BackupError::InvalidPassword => write!(f, "Invalid password"),
            BackupError::CorruptedBackup(e) => write!(f, "Corrupted backup: {e}"),
        }
    }
}

impl From<std::io::Error> for BackupError {
    fn from(e: std::io::Error) -> Self {
        BackupError::IoError(e)
    }
}

impl From<zip::result::ZipError> for BackupError {
    fn from(e: zip::result::ZipError) -> Self {
        BackupError::ZipError(e)
    }
}

impl From<serde_json::Error> for BackupError {
    fn from(e: serde_json::Error) -> Self {
        BackupError::JsonError(e)
    }
}

impl From<diesel::result::Error> for BackupError {
    fn from(e: diesel::result::Error) -> Self {
        BackupError::DatabaseError(e)
    }
}

/// Derive encryption key from password using PBKDF2
fn derive_key(password: &str, salt: &[u8]) -> [u8; 32] {
    let mut key = [0u8; 32];
    pbkdf2::derive(
        pbkdf2::PBKDF2_HMAC_SHA256,
        std::num::NonZeroU32::new(PBKDF2_ITERATIONS).unwrap(),
        salt,
        password.as_bytes(),
        &mut key,
    );
    key
}

/// Encrypt data using AES-256-GCM (same pattern as MFA encryption)
fn encrypt_data(data: &[u8], key: &[u8; 32]) -> Result<(Vec<u8>, [u8; NONCE_LEN]), BackupError> {
    let unbound_key = UnboundKey::new(&AES_256_GCM, key)
        .map_err(|_| BackupError::EncryptionError("Failed to create encryption key".to_string()))?;
    let sealing_key = LessSafeKey::new(unbound_key);

    // Generate random nonce
    let rng = SystemRandom::new();
    let mut nonce_bytes = [0u8; NONCE_LEN];
    rng.fill(&mut nonce_bytes)
        .map_err(|_| BackupError::EncryptionError("Failed to generate nonce".to_string()))?;
    let nonce = Nonce::assume_unique_for_key(nonce_bytes);

    // Encrypt the data
    let mut in_out = data.to_vec();
    sealing_key
        .seal_in_place_append_tag(nonce, Aad::empty(), &mut in_out)
        .map_err(|_| BackupError::EncryptionError("Encryption failed".to_string()))?;

    Ok((in_out, nonce_bytes))
}

/// Wrap a plaintext inner-zip blob in the encrypted outer
/// envelope: `NODB` magic, format version, fresh salt, fresh
/// nonce, then the AES-GCM ciphertext. The header is plaintext
/// by design so the reader can recognise the file before having
/// the password; everything that could leak schema info or row
/// counts lives inside the ciphertext.
fn seal_inner_zip(inner_zip: &[u8], password: &str) -> Result<Vec<u8>, BackupError> {
    let rng = SystemRandom::new();
    let mut salt = [0u8; SALT_LENGTH];
    rng.fill(&mut salt)
        .map_err(|_| BackupError::EncryptionError("Failed to generate salt".to_string()))?;

    let key = derive_key(password, &salt);
    let (ciphertext, nonce) = encrypt_data(inner_zip, &key)?;

    let mut out = Vec::with_capacity(ENCRYPTED_HEADER_LEN + ciphertext.len());
    out.extend_from_slice(ENCRYPTED_MAGIC);
    out.extend_from_slice(&BACKUP_FORMAT_VERSION.to_le_bytes());
    out.extend_from_slice(&salt);
    out.extend_from_slice(&nonce);
    out.extend_from_slice(&ciphertext);
    Ok(out)
}

/// Parse the encrypted outer envelope and return the plaintext
/// inner-zip bytes. The header is validated up front so a
/// malformed file fails fast with a clear error instead of a
/// generic decryption failure.
fn unseal_inner_zip(file_bytes: &[u8], password: &str) -> Result<Vec<u8>, BackupError> {
    if file_bytes.len() < ENCRYPTED_HEADER_LEN {
        return Err(BackupError::CorruptedBackup(
            "encrypted backup is shorter than its header".to_string(),
        ));
    }
    if &file_bytes[0..4] != ENCRYPTED_MAGIC {
        return Err(BackupError::CorruptedBackup(
            "missing NODB magic on encrypted backup".to_string(),
        ));
    }
    let version = u32::from_le_bytes(file_bytes[4..8].try_into().unwrap());
    if version != BACKUP_FORMAT_VERSION {
        return Err(BackupError::CorruptedBackup(format!(
            "unsupported backup format version {version}; this build expects {BACKUP_FORMAT_VERSION}"
        )));
    }
    let mut salt = [0u8; SALT_LENGTH];
    let mut nonce = [0u8; NONCE_LEN];
    salt.copy_from_slice(&file_bytes[8..8 + SALT_LENGTH]);
    nonce.copy_from_slice(&file_bytes[8 + SALT_LENGTH..ENCRYPTED_HEADER_LEN]);

    let key = derive_key(password, &salt);
    decrypt_data(&file_bytes[ENCRYPTED_HEADER_LEN..], &key, &nonce)
}

/// True when the file starts with the encrypted-wrapper magic.
/// Cheap byte check; callers use this to decide whether to
/// require a password.
fn is_encrypted_backup(backup_path: &Path) -> Result<bool, BackupError> {
    use std::io::Read as _;
    let mut f = File::open(backup_path)?;
    let mut magic = [0u8; 4];
    match f.read_exact(&mut magic) {
        Ok(()) => Ok(&magic == ENCRYPTED_MAGIC),
        // Shorter than 4 bytes — definitely not one of ours; let
        // the zip reader fail with its own message.
        Err(_) => Ok(false),
    }
}

/// Load the backup's inner zip bytes into memory. For plaintext
/// backups this is just the file contents; for encrypted ones
/// it's the result of unsealing the wrapper.
///
/// The whole zip lives in memory after this returns. That's
/// acceptable because the existing flow (which read every
/// `data/*.json` and `files/*` entry through `ZipArchive::by_name`)
/// already paged it all in, just with the kernel doing the work
/// instead of us.
fn load_inner_zip(backup_path: &Path, password: Option<&str>) -> Result<Vec<u8>, BackupError> {
    if is_encrypted_backup(backup_path)? {
        let bytes = fs::read(backup_path)?;
        let password = password.ok_or_else(|| {
            BackupError::EncryptionError("backup is encrypted; password is required".to_string())
        })?;
        unseal_inner_zip(&bytes, password)
    } else {
        Ok(fs::read(backup_path)?)
    }
}

/// Decrypt data using AES-256-GCM
fn decrypt_data(
    encrypted_data: &[u8],
    key: &[u8; 32],
    nonce_bytes: &[u8; NONCE_LEN],
) -> Result<Vec<u8>, BackupError> {
    let unbound_key = UnboundKey::new(&AES_256_GCM, key)
        .map_err(|_| BackupError::EncryptionError("Failed to create decryption key".to_string()))?;
    let opening_key = LessSafeKey::new(unbound_key);

    let nonce = Nonce::try_assume_unique_for_key(nonce_bytes)
        .map_err(|_| BackupError::EncryptionError("Invalid nonce".to_string()))?;

    // Decrypt
    let mut in_out = encrypted_data.to_vec();
    let plaintext = opening_key
        .open_in_place(nonce, Aad::empty(), &mut in_out)
        .map_err(|_| BackupError::InvalidPassword)?;

    Ok(plaintext.to_vec())
}

/// Export table data as JSON using raw SQL.
///
/// `table_name` is interpolated into the query directly because
/// Postgres doesn't accept identifiers as bound parameters. The
/// caller is responsible for passing only names that came from
/// `discover_user_tables`; we additionally validate against
/// `information_schema.tables` here as defence in depth so a
/// future caller can't accidentally widen the SQL-injection
/// surface.
/// Export one table's rows as a JSON-text payload. The row JSON
/// never passes through serde_json::Value, so numeric precision
/// (NUMERIC(12,3) → "10.000") is preserved verbatim. Sensitive-
/// field stripping runs inside Postgres via the `jsonb - 'key'`
/// operator.
fn export_table_data(
    conn: &mut DbConnection,
    table_name: &str,
    include_sensitive: bool,
) -> Result<(String, i64), BackupError> {
    use diesel::sql_query;
    use diesel::sql_types::Text;

    if !table_exists_in_db(conn, table_name)? {
        return Err(BackupError::CorruptedBackup(format!(
            "Refusing to export unknown table: {table_name}"
        )));
    }

    // Decide the per-row projection. With sensitive stripping,
    // the row goes through ::jsonb so the `- 'key'` operator can
    // run; back to ::text at the end for the wire format.
    let strip_fields: &[&str] = if include_sensitive {
        &[]
    } else {
        SENSITIVE_FIELDS
            .iter()
            .find(|(t, _)| *t == table_name)
            .map(|(_, fields)| *fields)
            .unwrap_or(&[])
    };

    let row_expr = if strip_fields.is_empty() {
        "row_to_json(t)::text".to_string()
    } else {
        let mut expr = "row_to_json(t)::jsonb".to_string();
        for f in strip_fields {
            // The stripped names come from the SENSITIVE_FIELDS
            // const so the value is fully under our control. We
            // still escape any embedded single quotes defensively.
            let escaped = f.replace('\'', "''");
            expr.push_str(&format!(" - '{escaped}'"));
        }
        format!("({expr})::text")
    };

    #[derive(QueryableByName)]
    struct JsonRow {
        #[diesel(sql_type = Text)]
        row_text: String,
    }

    let query = format!("SELECT {row_expr} AS row_text FROM {table_name} t");
    let results: Vec<JsonRow> = sql_query(&query).load(conn)?;

    // Assemble a JSON array as text. Each row_text is already a
    // valid JSON object (or null for empty rows, which shouldn't
    // happen). Joining with `,\n  ` keeps the on-disk format
    // mirror-image to the old pretty-printed output.
    let mut payload = String::from("[");
    for (i, row) in results.iter().enumerate() {
        if i > 0 {
            payload.push(',');
        }
        payload.push_str("\n  ");
        payload.push_str(&row.row_text);
    }
    if !results.is_empty() {
        payload.push('\n');
    }
    payload.push(']');

    let count = results.len() as i64;
    Ok((payload, count))
}

/// Get the uploads directory path
fn get_uploads_dir() -> PathBuf {
    std::env::var("UPLOAD_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("/app/uploads"))
}

/// Get the backups directory path
fn get_backups_dir() -> PathBuf {
    let base = std::env::var("UPLOAD_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("/app/uploads"));
    base.join("backups")
}

/// SHA-256 of arbitrary bytes, returned as lowercase hex. Used
/// for per-table integrity hashes in the backup manifest.
fn sha256_hex(bytes: &[u8]) -> String {
    use ring::digest::{digest, SHA256};
    hex::encode(digest(&SHA256, bytes).as_ref())
}

/// Create a backup export.
///
/// Builds the zip in memory and writes it to disk in one go.
/// When `password` is `Some`, the bytes are wrapped in the
/// AES-GCM envelope before writing (so the on-disk file is
/// `NODB...`). When `password` is `None`, the zip is written
/// as-is and sensitive fields are stripped from each table's
/// JSON.
pub fn create_backup(
    conn: &mut DbConnection,
    job_id: Uuid,
    password: Option<&str>,
) -> Result<PathBuf, BackupError> {
    let backups_dir = get_backups_dir();
    fs::create_dir_all(&backups_dir)?;

    let timestamp = Utc::now().format("%Y-%m-%d-%H%M%S");
    // Encrypted backups still carry the `.zip` extension because
    // the wrapped inner format IS a zip; the only difference is
    // the 52-byte header. Operators can still tell them apart
    // with `file` (zip vs data) but the extension stays familiar.
    let filename = format!("backup-{timestamp}.zip");
    let backup_path = backups_dir.join(&filename);

    let include_sensitive = password.is_some();
    let zip_bytes = build_inner_zip(conn, include_sensitive)?;

    let final_bytes = match password {
        Some(pw) => seal_inner_zip(&zip_bytes, pw)?,
        None => zip_bytes,
    };
    fs::write(&backup_path, &final_bytes)?;

    let file_size = final_bytes.len() as i64;
    backup_repo::update_backup_job(
        conn,
        job_id,
        BackupJobUpdate {
            status: Some("completed".to_string()),
            file_path: Some(backup_path.to_string_lossy().to_string()),
            file_size: Some(file_size),
            error_message: None,
            completed_at: Some(Utc::now().naive_utc()),
        },
    )?;

    Ok(backup_path)
}

/// Build the inner zip blob (the thing that gets either written
/// straight to disk or sealed by `seal_inner_zip`). Encapsulated
/// here so `create_backup` is small and the in-memory pipeline
/// is easy to audit.
fn build_inner_zip(
    conn: &mut DbConnection,
    include_sensitive: bool,
) -> Result<Vec<u8>, BackupError> {
    use std::io::Cursor;

    // Owned cursor over a Vec<u8> so we can pull the buffer back
    // out of the writer via `finish()` without lifetime gymnastics.
    let cursor: Cursor<Vec<u8>> = Cursor::new(Vec::new());
    let mut zip = ZipWriter::new(cursor);
    let options = FileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated)
        .unix_permissions(0o644);

    let mut table_manifests = HashMap::new();
    let tables_to_export = discover_user_tables(conn)?;

    for table_name in &tables_to_export {
        let table_name: &str = table_name;
        let (json_content, count) = export_table_data(conn, table_name, include_sensitive)?;
        let sha256 = sha256_hex(json_content.as_bytes());

        let path = format!("data/{table_name}.json");
        zip.start_file(&path, options)?;
        zip.write_all(json_content.as_bytes())?;

        table_manifests.insert(table_name.to_string(), TableManifest { count, sha256 });
    }

    // Files. Same skip-rules as before: avoid recursing into our
    // own backups dir, and skip thumbnails (cheap to regenerate
    // from the originals).
    let uploads_dir = get_uploads_dir();
    let mut file_count = 0i64;
    let mut total_size = 0i64;

    if uploads_dir.exists() {
        let thumbs_dir = uploads_dir.join("users").join("thumbs");
        for entry in WalkDir::new(&uploads_dir)
            .into_iter()
            .filter_entry(|e| {
                let path = e.path();
                !path.starts_with(get_backups_dir()) && !path.starts_with(&thumbs_dir)
            })
            .filter_map(|e| e.ok())
        {
            if entry.file_type().is_file() {
                let file_path = entry.path();
                let relative_path = file_path
                    .strip_prefix(&uploads_dir)
                    .map_err(|e| BackupError::IoError(std::io::Error::other(e.to_string())))?;
                let archive_path = format!("files/{}", relative_path.display());

                zip.start_file(&archive_path, options)?;
                let mut file = File::open(file_path)?;
                let mut buf = Vec::new();
                let size = file.read_to_end(&mut buf)?;
                zip.write_all(&buf)?;

                file_count += 1;
                total_size += size as i64;
            }
        }
    }

    let manifest = BackupManifest {
        backup_format_version: BACKUP_FORMAT_VERSION,
        nosdesk_version: env!("CARGO_PKG_VERSION").to_string(),
        schema_hash: SERVER_SCHEMA_HASH.to_string(),
        created_at: Utc::now().to_rfc3339(),
        tables: table_manifests,
        files: FilesManifest {
            total_count: file_count,
            total_size_bytes: total_size,
        },
    };

    let manifest_json = serde_json::to_string_pretty(&manifest)?;
    zip.start_file("manifest.json", options)?;
    zip.write_all(manifest_json.as_bytes())?;
    let finished = zip.finish()?;
    Ok(finished.into_inner())
}

/// Read and parse the manifest from a backup archive. For
/// encrypted backups the password is required (and acts as the
/// password verification — successful decryption is the proof).
pub fn read_backup_manifest(
    backup_path: &Path,
    password: Option<&str>,
) -> Result<BackupManifest, BackupError> {
    use std::io::Cursor;
    let inner = load_inner_zip(backup_path, password)?;
    let mut archive = ZipArchive::new(Cursor::new(inner))?;
    let mut manifest_file = archive.by_name("manifest.json")?;
    let mut manifest_content = String::new();
    manifest_file.read_to_string(&mut manifest_content)?;
    Ok(serde_json::from_str(&manifest_content)?)
}

/// Preview what a restore would do. Always decrypts when needed
/// (so a successful preview also proves the password works,
/// replacing the dropped `verify_backup_password` helper).
pub fn preview_restore(
    backup_path: &Path,
    password: Option<&str>,
) -> Result<RestorePreview, BackupError> {
    let encrypted = is_encrypted_backup(backup_path)?;
    let manifest = read_backup_manifest(backup_path, password)?;

    let mut warnings = Vec::new();

    if manifest.backup_format_version != BACKUP_FORMAT_VERSION {
        warnings.push(format!(
            "Backup format version {} differs from current ({}); restore will refuse",
            manifest.backup_format_version, BACKUP_FORMAT_VERSION
        ));
    }
    if manifest.schema_hash != SERVER_SCHEMA_HASH {
        warnings.push(format!(
            "Schema hash mismatch: backup={} server={}; pass --ignore-schema-mismatch to override",
            manifest.schema_hash, SERVER_SCHEMA_HASH
        ));
    }

    let current_version = env!("CARGO_PKG_VERSION");
    if manifest.nosdesk_version != current_version {
        warnings.push(format!(
            "Backup was created with Nosdesk v{}, current version is v{}",
            manifest.nosdesk_version, current_version
        ));
    }

    if manifest.files.total_size_bytes > 1024 * 1024 * 1024 {
        warnings.push(format!(
            "Backup contains {} GB of files, restore may take a while",
            manifest.files.total_size_bytes / (1024 * 1024 * 1024)
        ));
    }

    Ok(RestorePreview {
        manifest,
        encrypted,
        warnings,
    })
}

/// Restore files from a backup archive. For encrypted backups
/// the password is required to unwrap the outer envelope.
pub fn restore_backup_files(
    backup_path: &Path,
    password: Option<&str>,
) -> Result<u64, BackupError> {
    use std::io::Cursor;
    let inner = load_inner_zip(backup_path, password)?;
    let mut archive = ZipArchive::new(Cursor::new(inner))?;

    let uploads_dir = get_uploads_dir();
    let mut restored_count = 0u64;

    for i in 0..archive.len() {
        let mut file = archive.by_index(i)?;
        let name = file.name().to_string();

        if name.starts_with("files/") && !name.ends_with('/') {
            let relative_path = name.strip_prefix("files/").unwrap();
            let dest_path = uploads_dir.join(relative_path);

            if let Some(parent) = dest_path.parent() {
                fs::create_dir_all(parent)?;
            }

            let mut dest_file = File::create(&dest_path)?;
            std::io::copy(&mut file, &mut dest_file)?;
            restored_count += 1;
        }
    }

    Ok(restored_count)
}

/// Delete a backup file
pub fn delete_backup_file(file_path: &str) -> Result<(), BackupError> {
    let path = Path::new(file_path);
    if path.exists() {
        fs::remove_file(path)?;
    }
    Ok(())
}

/// Stats from database restore.
#[derive(Debug, Default, serde::Serialize)]
pub struct RestoreStats {
    pub tables_restored: usize,
    pub records_restored: usize,
    /// Per-table breakdown so the operator can see exactly which
    /// rows landed where. With the single-transaction-on-abort
    /// flow this is always a complete picture (no partial
    /// commits), but it's still load-bearing for operator
    /// confidence after a successful restore.
    pub per_table: Vec<TableRestoreResult>,
}

#[derive(Debug, serde::Serialize)]
pub struct TableRestoreResult {
    pub table: String,
    pub rows_attempted: usize,
    pub rows_loaded: usize,
}

/// Knobs for [`restore_database`]. New options should default
/// to the safer behaviour so a caller that doesn't pass one
/// gets the locked-down path.
#[derive(Debug, Default)]
pub struct RestoreOptions {
    /// Bypass the empty-target-database precheck. The CLI
    /// exposes this as `--force`; the web handler sets it
    /// implicitly because admin-auth is the upstream gate.
    pub force_non_empty: bool,
    /// Bypass the schema-hash check. The backup carries the
    /// hash of the migrations directory it was taken at; the
    /// server compares against its own compile-time hash and
    /// refuses on mismatch by default. Operators who know the
    /// schemas are compatible (e.g. a no-op migration was
    /// added between versions) can pass `--ignore-schema-mismatch`.
    pub ignore_schema_mismatch: bool,
}

/// Restore tables from a backup archive into the live database.
///
/// Runs inside a single transaction with
/// `session_replication_role = 'replica'`, so:
///
///   - The whole restore is atomic. A FK violation on row #501
///     of a 1000-row table rolls back rows 1..500 of that table
///     and every prior table in the same call. The operator
///     never sees a half-restored database.
///   - FK ordering between tables is a non-issue: the trigger
///     suspension covers FK + user triggers but not UNIQUE /
///     CHECK constraints, so structurally-bad rows still fail.
///   - The restore order comes from `discover_user_tables`
///     against the live schema, intersected with what's in the
///     backup. Tables in the backup that don't exist on the
///     live DB are skipped with a warning (forward-compat
///     scenarios). Tables that exist live but aren't in the
///     backup are left empty.
///
/// Pre-flight: refuses on a non-empty users table unless the
/// caller sets `options.force_non_empty`. The CLI exposes this
/// as `--force`; the web admin endpoint sets it implicitly.
pub fn restore_database(
    conn: &mut DbConnection,
    backup_path: &Path,
    password: Option<&str>,
    options: RestoreOptions,
) -> Result<RestoreStats, BackupError> {
    use diesel::connection::Connection;
    use diesel::deserialize::QueryableByName;
    use diesel::prelude::*;
    use diesel::sql_query;
    use diesel::sql_types::BigInt;
    use std::io::Cursor;

    // ---- Phase 1: load the inner zip (decrypts if encrypted) ----
    let inner_zip = load_inner_zip(backup_path, password)?;
    let mut archive = ZipArchive::new(Cursor::new(inner_zip))?;

    // ---- Phase 2: read + validate manifest ----
    let manifest: BackupManifest = {
        let mut manifest_file = archive.by_name("manifest.json")?;
        let mut content = String::new();
        manifest_file.read_to_string(&mut content)?;
        serde_json::from_str(&content)?
    };

    if manifest.backup_format_version != BACKUP_FORMAT_VERSION {
        return Err(BackupError::CorruptedBackup(format!(
            "unsupported backup format version {} (this build expects {})",
            manifest.backup_format_version, BACKUP_FORMAT_VERSION
        )));
    }
    if manifest.schema_hash != SERVER_SCHEMA_HASH && !options.ignore_schema_mismatch {
        return Err(BackupError::CorruptedBackup(format!(
            "schema hash mismatch (backup={}, server={}); pass --ignore-schema-mismatch to override",
            manifest.schema_hash, SERVER_SCHEMA_HASH
        )));
    }

    // ---- Phase 3: pre-flight empty-target check ----
    if !options.force_non_empty {
        #[derive(QueryableByName)]
        struct CountRow {
            #[diesel(sql_type = BigInt)]
            n: i64,
        }
        let count: CountRow = sql_query("SELECT COUNT(*)::bigint AS n FROM users")
            .get_result(conn)
            .map_err(BackupError::DatabaseError)?;
        if count.n > 0 {
            return Err(BackupError::CorruptedBackup(format!(
                "target database is not empty ({} existing users); pass --force to overwrite",
                count.n
            )));
        }
    }

    // ---- Phase 4: figure out what to restore ----
    let live_tables: std::collections::HashSet<String> =
        discover_user_tables(conn)?.into_iter().collect();
    // Skip partition children if a backup carries them; the
    // parent's rows route to the right child on insert.
    let partition_children = partition_children(conn)?;
    let mut backup_tables: Vec<String> = manifest.tables.keys().cloned().collect();
    backup_tables.sort();

    let mut skipped_unknown: Vec<String> = Vec::new();
    let mut skipped_partition: Vec<String> = Vec::new();
    let restore_order: Vec<String> = backup_tables
        .into_iter()
        .filter(|t| {
            if partition_children.contains(t) {
                skipped_partition.push(t.clone());
                return false;
            }
            if live_tables.contains(t) {
                true
            } else {
                skipped_unknown.push(t.clone());
                false
            }
        })
        .collect();
    for name in &skipped_unknown {
        log::warn!(
            "restore: skipping table '{name}' that is in the backup but not in the live schema (likely a forward-compat scenario)"
        );
    }
    for name in &skipped_partition {
        log::info!(
            "restore: skipping partition child '{name}'; parent table covers its rows on restore"
        );
    }

    // ---- Phase 5: load + hash-check every table BEFORE the
    //              transaction. The payload stays as raw JSON
    //              text and is bound to the restore INSERT
    //              server-side; routing it through
    //              `serde_json::Value` here would coerce numbers
    //              into f64 and lose NUMERIC precision (a JSONB
    //              column holding 10.000 would come back 10.0).
    let mut table_payloads: Vec<(String, String, usize)> = Vec::with_capacity(restore_order.len());
    for table_name in &restore_order {
        let data_path = format!("data/{table_name}.json");
        let content = match archive.by_name(&data_path) {
            Ok(mut data_file) => {
                let mut buf = String::new();
                data_file.read_to_string(&mut buf)?;
                buf
            }
            Err(_) => continue,
        };

        let expected = &manifest
            .tables
            .get(table_name)
            .expect("table present in restore_order is in manifest by construction")
            .sha256;
        let actual = sha256_hex(content.as_bytes());
        if &actual != expected {
            return Err(BackupError::CorruptedBackup(format!(
                "sha256 mismatch for table '{table_name}': manifest={expected} computed={actual}"
            )));
        }

        let row_count = manifest
            .tables
            .get(table_name)
            .map(|m| m.count as usize)
            .unwrap_or(0);
        table_payloads.push((table_name.clone(), content, row_count));
    }

    // ---- Phase 6: single transaction with FK + trigger
    //              suppression. First row failure rolls back
    //              the entire restore.
    conn.transaction::<RestoreStats, BackupError, _>(|c| {
        sql_query("SET LOCAL session_replication_role = 'replica'")
            .execute(c)
            .map_err(BackupError::DatabaseError)?;

        // Clear migration-seeded rows from the tables we're
        // about to restore so explicit IDs in the backup don't
        // collide.
        if !table_payloads.is_empty() {
            let names: Vec<String> = table_payloads
                .iter()
                .map(|(n, _, _)| format!("\"{}\"", n.replace('"', "\"\"")))
                .collect();
            let stmt = format!(
                "TRUNCATE TABLE {} RESTART IDENTITY CASCADE",
                names.join(", ")
            );
            sql_query(&stmt)
                .execute(c)
                .map_err(BackupError::DatabaseError)?;
        }

        let mut stats = RestoreStats::default();

        for (table_name, payload, rows_attempted) in &table_payloads {
            if *rows_attempted == 0 {
                stats.per_table.push(TableRestoreResult {
                    table: table_name.clone(),
                    rows_attempted: 0,
                    rows_loaded: 0,
                });
                continue;
            }
            let rows_loaded = restore_table_data(c, table_name, payload)?;
            if rows_loaded > 0 {
                stats.tables_restored += 1;
                stats.records_restored += rows_loaded;
            }
            stats.per_table.push(TableRestoreResult {
                table: table_name.clone(),
                rows_attempted: *rows_attempted,
                rows_loaded,
            });
        }

        // setval is transactional in PG 18; rollback unwinds it.
        reset_sequences(c)?;
        Ok(stats)
    })
}

/// Re-align every column-owned sequence to MAX(col)+1. Sourced
/// from `pg_depend` so any serial / bigserial / identity column
/// is covered without a hand-maintained list.
fn reset_sequences(conn: &mut DbConnection) -> Result<(), BackupError> {
    use diesel::deserialize::QueryableByName;
    use diesel::prelude::*;
    use diesel::sql_query;
    use diesel::sql_types::Text;

    #[derive(QueryableByName)]
    struct SequenceOwner {
        #[diesel(sql_type = Text)]
        seq_qualified: String,
        #[diesel(sql_type = Text)]
        table_qualified: String,
        #[diesel(sql_type = Text)]
        column_name: String,
    }

    // Resolve every sequence that's `OWNED BY` a column. The
    // serial / bigserial / identity machinery all wire through
    // pg_depend with deptype='a' (auto). Restricted to public
    // schema and to numeric columns so the setval cast below
    // is safe.
    let owners: Vec<SequenceOwner> = sql_query(
        "SELECT \
             format('%I.%I', n.nspname, c.relname) AS seq_qualified, \
             format('%I.%I', tn.nspname, t.relname) AS table_qualified, \
             a.attname AS column_name \
         FROM pg_class c \
         JOIN pg_namespace n ON n.oid = c.relnamespace \
         JOIN pg_depend d \
           ON d.objid = c.oid \
          AND d.classid = 'pg_class'::regclass \
          AND d.refclassid = 'pg_class'::regclass \
          AND d.deptype = 'a' \
         JOIN pg_class t ON t.oid = d.refobjid \
         JOIN pg_namespace tn ON tn.oid = t.relnamespace \
         JOIN pg_attribute a \
           ON a.attrelid = t.oid \
          AND a.attnum = d.refobjsubid \
         WHERE c.relkind = 'S' \
           AND n.nspname = 'public' \
           AND tn.nspname = 'public'",
    )
    .load(conn)
    .map_err(BackupError::DatabaseError)?;

    for SequenceOwner {
        seq_qualified,
        table_qualified,
        column_name,
    } in owners
    {
        let stmt = format!(
            "SELECT setval('{seq_qualified}', COALESCE((SELECT MAX(\"{column_name}\") FROM {table_qualified}), 0) + 1, false)"
        );
        if let Err(e) = sql_query(&stmt).execute(conn) {
            log::warn!(
                "reset_sequences: failed to reset {seq_qualified} (owner {table_qualified}.{column_name}): {e}"
            );
        }
    }

    log::info!("reset_sequences: aligned all owned sequences to MAX+1");
    Ok(())
}

/// Restore one table's rows. The JSON array payload travels as
/// raw text and is cast to jsonb server-side via `$1::jsonb` so
/// Postgres's own JSON parser handles numeric values
/// (NUMERIC(12,3) → "10.000" stays "10.000"). Round-tripping
/// through `serde_json::Value` would coerce numbers into f64
/// and lose precision.
///
/// `jsonb_populate_recordset(NULL::table, ...)` then runs the
/// per-column conversion against the target record type. Extra
/// JSON keys are ignored; missing keys default to NULL.
fn restore_table_data(
    conn: &mut DbConnection,
    table_name: &str,
    payload: &str,
) -> Result<usize, BackupError> {
    use diesel::prelude::*;
    use diesel::sql_query;
    use diesel::sql_types::Text;

    if !table_exists_in_db(conn, table_name)? {
        return Err(BackupError::CorruptedBackup(format!(
            "backup references unknown table '{table_name}'"
        )));
    }
    if payload.is_empty() || payload.trim() == "[]" {
        return Ok(0);
    }

    if !table_name
        .chars()
        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
    {
        return Err(BackupError::CorruptedBackup(format!(
            "unsafe table identifier '{table_name}'"
        )));
    }

    let stmt = format!(
        "INSERT INTO public.{table_name} \
         SELECT * FROM jsonb_populate_recordset(NULL::public.{table_name}, $1::jsonb)"
    );
    let count = sql_query(&stmt)
        .bind::<Text, _>(payload)
        .execute(conn)
        .map_err(|e| {
            BackupError::DatabaseError(diesel::result::Error::QueryBuilderError(
                format!("table '{table_name}' restore failed: {e}").into(),
            ))
        })?;
    Ok(count)
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── derive_key ───────────────────────────────────────────────

    #[test]
    fn derive_key_produces_32_bytes() {
        let key = derive_key("password", b"saltsaltsaltsalt");
        assert_eq!(key.len(), 32);
    }

    #[test]
    fn derive_key_is_deterministic() {
        let salt = b"fixed-salt-value-for-test1234567";
        let k1 = derive_key("pass", salt);
        let k2 = derive_key("pass", salt);
        assert_eq!(k1, k2);
    }

    #[test]
    fn derive_key_differs_for_different_passwords() {
        let salt = b"fixed-salt-value-for-test1234567";
        let k1 = derive_key("password1", salt);
        let k2 = derive_key("password2", salt);
        assert_ne!(k1, k2);
    }

    // ── encrypt_data / decrypt_data roundtrip ────────────────────

    #[test]
    fn encrypt_decrypt_roundtrip() {
        let key = derive_key("test-password", b"salt-for-encrypt-decrypt-test!!");
        let plaintext = b"hello world, this is secret data";
        let (ciphertext, nonce) = encrypt_data(plaintext, &key).unwrap();
        assert_ne!(&ciphertext[..plaintext.len()], plaintext);

        let decrypted = decrypt_data(&ciphertext, &key, &nonce).unwrap();
        assert_eq!(decrypted, plaintext);
    }

    #[test]
    fn decrypt_with_wrong_key_fails() {
        let key = derive_key("correct", b"salt-for-wrong-key-test!!!!!!!!");
        let wrong_key = derive_key("wrong", b"salt-for-wrong-key-test!!!!!!!!");
        let (ciphertext, nonce) = encrypt_data(b"secret", &key).unwrap();
        assert!(decrypt_data(&ciphertext, &wrong_key, &nonce).is_err());
    }

    // ── table allowlist (AUD-008, post-introspection rewrite) ────

    #[test]
    fn table_exists_in_db_accepts_real_tables() {
        use crate::test_helpers::setup_test_connection;
        let mut conn = setup_test_connection();
        // `users` is the load-bearing table that the rest of the
        // system depends on; if it's missing from the test DB
        // we've got bigger problems than this test.
        assert!(table_exists_in_db(&mut conn, "users").unwrap());
        assert!(table_exists_in_db(&mut conn, "tickets").unwrap());
    }

    #[test]
    fn table_exists_in_db_rejects_unknown_or_hostile_names() {
        use crate::test_helpers::setup_test_connection;
        let mut conn = setup_test_connection();
        for hostile in [
            "",
            "pg_authid", // exists in pg_catalog, not public
            "users; DROP TABLE users; --",
            "users) RETURNING *; --",
            "USERS", // case-sensitive in PG; public.users is lowercase
            "Users",
            "schema.users",
            "secret_table",
            "__diesel_schema_migrations", // in EXCLUDE list at discover time, but still exists; the test guards the WRONG-table path
        ] {
            if hostile == "__diesel_schema_migrations" {
                // The exclude list is enforced at *discover* time
                // (so we don't BACK UP it), not at *exists* time
                // (it's a real table in the DB). Skip this one;
                // it would pass `table_exists_in_db` correctly.
                continue;
            }
            assert!(
                !table_exists_in_db(&mut conn, hostile).unwrap(),
                "expected rejection for {hostile:?}"
            );
        }
    }

    #[test]
    fn discover_user_tables_excludes_diesel_migrations() {
        use crate::test_helpers::setup_test_connection;
        let mut conn = setup_test_connection();
        let tables = discover_user_tables(&mut conn).unwrap();
        assert!(!tables.iter().any(|t| t == "__diesel_schema_migrations"));
        // Sanity: discovers core user tables.
        assert!(tables.iter().any(|t| t == "users"));
        assert!(tables.iter().any(|t| t == "tickets"));
        // The bug that started this rewrite: channels table must
        // now be discovered automatically.
        assert!(
            tables.iter().any(|t| t == "channels"),
            "channels table must be in the backup discovery (this is the AUD-014 regression guard)"
        );
    }

    // ── DB-backed: poisoned-backup defence (AUD-008) ─────────────

    #[test]
    fn restore_table_data_ignores_hostile_column_names() {
        // A poisoned backup might ship a row whose JSON keys carry
        // SQL fragments instead of real column names. With the
        // pre-AUD-008 string-concatenation pattern this would have
        // landed straight in the INSERT statement. With
        // jsonb_populate_record, unknown keys are silently dropped
        // and Postgres treats them as no-ops. This test confirms:
        // (a) the legitimate column data is restored intact, and
        // (b) the hostile keys aren't executed (the users table
        //     still exists, no extra rows appear, etc).
        use crate::test_helpers::setup_test_connection;
        use diesel::prelude::*;
        use uuid::Uuid;

        let mut conn = setup_test_connection();

        let uuid = Uuid::new_v4();
        // Full row shape, matching what a real backup would
        // capture. `jsonb_populate_recordset` writes NULL for
        // missing keys, so the JSON must spell out the NOT NULL
        // columns explicitly. The hostile keys at the end are
        // what we're actually testing.
        let row = serde_json::json!({
            "uuid": uuid,
            "name": "Restored Alice",
            "role": "user",
            "feature_flag_overrides": {},
            "mfa_enabled": false,
            "created_at": "2026-01-01T00:00:00",
            "updated_at": "2026-01-01T00:00:00",
            "name); DROP TABLE users; --": "ignored",
            "id, mfa_enabled) VALUES (1,true": 42,
            "); SELECT pg_sleep(60)--": null,
        });

        let payload = serde_json::to_string(&[row]).expect("serialize row");
        let inserted = restore_table_data(&mut conn, "users", &payload)
            .expect("restore_table_data should not fail");
        assert_eq!(inserted, 1, "exactly one row inserted");

        // The legit row landed with the right name.
        let name: String = crate::schema::users::table
            .filter(crate::schema::users::uuid.eq(uuid))
            .select(crate::schema::users::name)
            .first(&mut conn)
            .expect("inserted user should be readable");
        assert_eq!(name, "Restored Alice");

        // The hostile-named columns weren't created; the users table
        // shape is whatever the schema says. A simple count query
        // succeeding confirms the table wasn't dropped or mutated.
        let count: i64 = crate::schema::users::table
            .count()
            .get_result(&mut conn)
            .expect("users table should still be queryable");
        assert!(count >= 1, "users table intact after hostile insert");
    }
}
