//! Restoring a backup an earlier Nosdesk made.
//!
//! A backup's rows have the shape of the schema it was taken at. Restore
//! doesn't patch them up to this build's schema column by column: migrations
//! move data as well as add columns (merges into `ticket_merges`, revoked
//! sign-in tokens, seeded notification types), and only running them does
//! what an in-place upgrade does. So an older backup loads into a scratch
//! database migrated to the backup's own point, the later migrations run over
//! it, and the result is exported again and restored like a backup from this
//! build. The live database isn't touched until that last step.
//!
//! The backup's point is read from its manifest: the last migration it was
//! taken at and a SHA-256 of the migrations up to it (`build.rs`). 1.0.x
//! manifests carry neither, only a fingerprint from a hasher that can change
//! with the toolchain, so their three possible values are pinned below.

use std::fmt;

use diesel::prelude::*;
use diesel::sql_query;
use diesel_migrations::MigrationHarness;

use super::backup::BackupError;
use crate::db::DbConnection;
use crate::models::BackupManifest;

/// One prefix of this build's migrations: the version of its last migration
/// and the SHA-256 of every migration file up to it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MigrationPrefix {
    pub version: &'static str,
    pub sha256: &'static str,
}

/// Every prefix of this build's migrations, oldest first. Generated by
/// `build.rs`; the last entry is this build's own schema.
pub const MIGRATION_PREFIXES: &[MigrationPrefix] =
    include!(concat!(env!("OUT_DIR"), "/migration_schema.rs"));

/// This build's schema: the last migration and the digest of all of them.
pub fn current_schema() -> MigrationPrefix {
    *MIGRATION_PREFIXES
        .last()
        .expect("build.rs lists at least the initial migration")
}

/// A schema point 1.0.x backups name by `build.rs`'s old fingerprint alone.
struct LegacySchemaPoint {
    /// The manifest's `schema_hash`, as 1.0.x wrote it.
    schema_hash: &'static str,
    /// The last migration those releases shipped.
    migration: &'static str,
    /// [`MIGRATION_PREFIXES`]' digest for `migration`, pinned so an edit to
    /// a shipped migration fails the test below rather than mislabel a backup.
    prefix_sha256: &'static str,
}

/// Every 1.0.x schema. Never recomputed: the fingerprint came from Rust's
/// `DefaultHasher`, which a toolchain upgrade may change.
const LEGACY_SCHEMA_POINTS: &[LegacySchemaPoint] = &[
    // 1.0.0 to 1.0.6 (there was no 1.0.7)
    LegacySchemaPoint {
        schema_hash: "bfd48f513ed7ebd7",
        migration: "00000000000000",
        prefix_sha256: "221d5c7558791ade1bcea8ab79919b5d74b6f2cdb47e551fbbe99f2cbf494650",
    },
    // 1.0.8 to 1.0.10
    LegacySchemaPoint {
        schema_hash: "be184d8bc927013a",
        migration: "20260616000000",
        prefix_sha256: "a5741f6f309b811aa789b8aa6eb0931b873fa303aa511a45b35ae72cf77ad2e5",
    },
    // 1.0.11 to 1.0.13
    LegacySchemaPoint {
        schema_hash: "0319c33351b4a3c4",
        migration: "20260618100000",
        prefix_sha256: "61befb0f1c40d3d55c3600d26200c0c7a2acc7f8c07497f839cfb33d77b97d77",
    },
];

/// A release from 1.1.0 on, whose backups name their migration and digest.
/// Read by the shipped-schema test.
#[cfg_attr(not(test), allow(dead_code))]
struct ReleasedSchemaPoint {
    #[allow(dead_code)] // names the release for whoever reads the list
    release: &'static str,
    migration: &'static str,
    prefix_sha256: &'static str,
}

/// Every release since 1.1.0 that shipped a new migration, pinned like the
/// 1.0.x points so editing or inserting a shipped migration fails CI rather
/// than leave that release's backups unrestorable. Add the release here when
/// it is tagged (DEVELOPMENT.md, "Releases"); 1.1.0 is the first.
#[cfg_attr(not(test), allow(dead_code))]
const RELEASED_SCHEMA_POINTS: &[ReleasedSchemaPoint] = &[];

/// Where a backup's schema sits relative to this build's.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SchemaPoint {
    /// Taken at this build's schema: restores as it is.
    Current,
    /// Taken at an earlier schema, ending at `migration`: upgraded on restore.
    Earlier { migration: &'static str },
}

/// Why a backup can't be restored here.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum NotRestorable {
    /// A later Nosdesk made it.
    Newer { backup_version: String },
    /// Its schema isn't one of this build's migration points: a development
    /// build, or migrations that were edited after they shipped.
    Unknown { backup_version: String },
}

impl fmt::Display for NotRestorable {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let current = env!("CARGO_PKG_VERSION");
        match self {
            NotRestorable::Newer { backup_version } => write!(
                f,
                "this backup was made by Nosdesk {backup_version}, which is newer than this \
                 server ({current}); upgrade Nosdesk, then restore it"
            ),
            NotRestorable::Unknown { backup_version } => write!(
                f,
                "this backup (Nosdesk {backup_version}) holds a database layout this server \
                 doesn't recognise; it restores backups made by Nosdesk 1.0.0 to {current}"
            ),
        }
    }
}

/// The schema point `manifest` was taken at.
pub fn schema_point(manifest: &BackupManifest) -> Result<SchemaPoint, NotRestorable> {
    let backup_version = || manifest.nosdesk_version.clone();
    let current = current_schema();

    if let (Some(version), Some(sha256)) = (&manifest.migration_version, &manifest.schema_sha256) {
        return match MIGRATION_PREFIXES.iter().find(|p| p.version == version) {
            Some(prefix) if prefix.sha256 != sha256 => Err(NotRestorable::Unknown {
                backup_version: backup_version(),
            }),
            Some(prefix) if prefix.version == current.version => Ok(SchemaPoint::Current),
            Some(prefix) => Ok(SchemaPoint::Earlier {
                migration: prefix.version,
            }),
            None if version.as_str() > current.version => Err(NotRestorable::Newer {
                backup_version: backup_version(),
            }),
            None => Err(NotRestorable::Unknown {
                backup_version: backup_version(),
            }),
        };
    }

    // A manifest without them: 1.0.x, or a build of this version from before
    // they were recorded (same fingerprint as this build).
    if manifest.schema_hash == env!("NOSDESK_SCHEMA_HASH") {
        return Ok(SchemaPoint::Current);
    }
    if let Some(point) = LEGACY_SCHEMA_POINTS
        .iter()
        .find(|p| p.schema_hash == manifest.schema_hash)
    {
        // Only while this build's migrations up to that point are the ones
        // those releases shipped.
        let shipped = MIGRATION_PREFIXES
            .iter()
            .any(|p| p.version == point.migration && p.sha256 == point.prefix_sha256);
        return if shipped {
            Ok(SchemaPoint::Earlier {
                migration: point.migration,
            })
        } else {
            Err(NotRestorable::Unknown {
                backup_version: backup_version(),
            })
        };
    }
    if is_newer_release(&manifest.nosdesk_version) {
        return Err(NotRestorable::Newer {
            backup_version: backup_version(),
        });
    }
    Err(NotRestorable::Unknown {
        backup_version: backup_version(),
    })
}

/// Whether `version` is a later release than this build.
fn is_newer_release(version: &str) -> bool {
    match (
        semver::Version::parse(version),
        semver::Version::parse(env!("CARGO_PKG_VERSION")),
    ) {
        (Ok(backup), Ok(current)) => backup > current,
        _ => false,
    }
}

/// Upgrade the rows of `inner_zip`, a backup taken at `migration`, to this
/// build's schema. Returns the upgraded rows as an archive without files.
///
/// Runs in a scratch database on the server `conn` is on, reached through
/// `server_url`, and always drops it. `conn` itself only creates and drops
/// that database; the live data is untouched.
pub(crate) fn upgrade_archive(
    conn: &mut DbConnection,
    server_url: &str,
    inner_zip: &[u8],
    migration: &str,
    chunk_bytes: usize,
) -> Result<Vec<u8>, BackupError> {
    let scratch = ScratchDatabase::create(conn, server_url)?;
    let pool = r2d2::Pool::builder()
        .max_size(1)
        .build(crate::db::ResettingManager::new(scratch.url.clone()))
        .map_err(|e| {
            BackupError::UpgradeFailed(format!("connecting to the scratch database: {e}"))
        })?;
    let mut scratch_conn = pool.get().map_err(|e| {
        BackupError::UpgradeFailed(format!("connecting to the scratch database: {e}"))
    })?;

    migrate(&mut scratch_conn, Some(migration))?;
    super::backup::load_archive(
        &mut scratch_conn,
        inner_zip,
        super::backup::LoadInto::Scratch,
        &[],
        chunk_bytes,
    )?;
    migrate(&mut scratch_conn, None)?;
    let upgraded = super::backup::build_inner_zip(&mut scratch_conn, true, false)?;

    drop(scratch_conn);
    drop(pool);
    drop(scratch);
    Ok(upgraded)
}

/// Refuse early, before anything is touched, when the role restore runs as
/// isn't a superuser. The scratch database starts from template0, so the
/// upgrade runs every migration from the first, as a fresh install does, and
/// that takes a superuser: the initial schema disables system triggers and
/// grants role membership, and the load sets `session_replication_role`.
/// CREATEDB and BYPASSRLS without superuser aren't enough.
pub(crate) fn require_upgrade_privileges(conn: &mut DbConnection) -> Result<(), BackupError> {
    #[derive(QueryableByName)]
    struct Role {
        #[diesel(sql_type = diesel::sql_types::Bool)]
        rolsuper: bool,
    }
    let role: Role = sql_query("SELECT rolsuper FROM pg_roles WHERE rolname = current_user")
        .get_result(conn)
        .map_err(BackupError::DatabaseError)?;
    if role.rolsuper {
        Ok(())
    } else {
        Err(BackupError::NeedsSuperuser)
    }
}

/// The name prefix of the scratch databases a restore of the database `conn`
/// is on creates: tied to that database, so restores of another database on
/// the same server never touch them.
fn scratch_prefix(conn: &mut DbConnection) -> Result<String, BackupError> {
    #[derive(QueryableByName)]
    struct Oid {
        #[diesel(sql_type = diesel::sql_types::Text)]
        oid: String,
    }
    let row: Oid =
        sql_query("SELECT oid::text AS oid FROM pg_database WHERE datname = current_database()")
            .get_result(conn)
            .map_err(BackupError::DatabaseError)?;
    Ok(format!("nosdesk_restore_{}_", row.oid))
}

/// Drop scratch databases an earlier restore of this database left behind,
/// as one killed mid-upgrade does. Runs under the restore lock, so none of
/// them is in use. Best effort: a role that can't drop them only logs.
pub(crate) fn drop_leftover_scratch_databases(conn: &mut DbConnection) {
    #[derive(QueryableByName)]
    struct Name {
        #[diesel(sql_type = diesel::sql_types::Text)]
        datname: String,
    }
    let leftovers = scratch_prefix(conn).and_then(|prefix| {
        sql_query("SELECT datname::text AS datname FROM pg_database WHERE starts_with(datname, $1)")
            .bind::<diesel::sql_types::Text, _>(prefix)
            .load::<Name>(conn)
            .map_err(BackupError::DatabaseError)
    });
    let leftovers = match leftovers {
        Ok(names) => names,
        Err(e) => {
            tracing::warn!(error = %e, "restore: couldn't list leftover scratch databases");
            return;
        }
    };
    for Name { datname } in leftovers {
        let dropped = sql_query(format!(
            "DROP DATABASE IF EXISTS \"{}\" WITH (FORCE)",
            datname.replace('"', "\"\"")
        ))
        .execute(conn);
        match dropped {
            Ok(_) => {
                tracing::info!(scratch_database = %datname, "restore: dropped a leftover scratch database")
            }
            Err(e) => tracing::warn!(
                scratch_database = %datname,
                error = %e,
                "restore: couldn't drop a leftover scratch database"
            ),
        }
    }
}

/// Apply this build's pending migrations to `conn`, up to and including
/// `up_to` when given. Each runs in its own transaction, as on boot: two of
/// them add enum values that a later one uses, which one transaction can't do.
fn migrate(conn: &mut DbConnection, up_to: Option<&str>) -> Result<(), BackupError> {
    let mut pending = conn
        .pending_migrations(crate::db::MIGRATIONS)
        .map_err(|e| BackupError::UpgradeFailed(format!("listing migrations: {e}")))?;
    pending.sort_by_key(|m| m.name().version().to_string());
    for migration in pending {
        let version = migration.name().version().to_string();
        if up_to.is_some_and(|last| version.as_str() > last) {
            break;
        }
        conn.run_migration(&*migration).map_err(|e| {
            BackupError::UpgradeFailed(format!("migration {} failed: {e}", migration.name()))
        })?;
    }
    Ok(())
}

/// A throwaway database on the live server, dropped with this value, also
/// when a step fails or panics.
struct ScratchDatabase {
    name: String,
    url: String,
    server_url: String,
}

impl ScratchDatabase {
    fn create(conn: &mut DbConnection, server_url: &str) -> Result<Self, BackupError> {
        let name = format!(
            "{}{}",
            scratch_prefix(conn)?,
            &uuid::Uuid::new_v4().simple().to_string()[..16]
        );
        // template0: a clean database, whatever extensions template1 carries.
        sql_query(format!("CREATE DATABASE \"{name}\" TEMPLATE template0"))
            .execute(conn)
            .map_err(|e| {
                BackupError::UpgradeFailed(format!("creating the scratch database: {e}"))
            })?;
        Ok(Self {
            url: with_database(server_url, &name),
            name,
            server_url: server_url.to_string(),
        })
    }
}

impl Drop for ScratchDatabase {
    fn drop(&mut self) {
        let statement = format!("DROP DATABASE IF EXISTS \"{}\" WITH (FORCE)", self.name);
        let result = match PgConnection::establish(&self.server_url) {
            Ok(mut conn) => sql_query(statement)
                .execute(&mut conn)
                .map(|_| ())
                .map_err(|e| e.to_string()),
            Err(e) => Err(e.to_string()),
        };
        if let Err(e) = result {
            tracing::error!(
                scratch_database = %self.name,
                error = %e,
                "restore: couldn't drop the scratch database; drop it by hand"
            );
        }
    }
}

/// `url` with its database swapped for `database`. A `postgres://` URL gets a
/// new path; a `key=value` connection string gets a `dbname`, which overrides
/// an earlier one.
fn with_database(url: &str, database: &str) -> String {
    match url::Url::parse(url) {
        Ok(mut parsed) if matches!(parsed.scheme(), "postgres" | "postgresql") => {
            parsed.set_path(&format!("/{database}"));
            parsed.to_string()
        }
        _ => format!("{url} dbname={database}"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::FilesManifest;

    fn manifest(
        nosdesk_version: &str,
        schema_hash: &str,
        point: Option<(&str, &str)>,
    ) -> BackupManifest {
        BackupManifest {
            backup_format_version: 2,
            nosdesk_version: nosdesk_version.to_string(),
            schema_hash: schema_hash.to_string(),
            migration_version: point.map(|(v, _)| v.to_string()),
            schema_sha256: point.map(|(_, s)| s.to_string()),
            created_at: String::new(),
            tables: Default::default(),
            files: FilesManifest {
                total_count: 0,
                total_size_bytes: 0,
            },
        }
    }

    #[test]
    fn migration_prefixes_list_every_embedded_migration_in_order() {
        use diesel::migration::MigrationSource;
        let embedded: Vec<String> =
            MigrationSource::<diesel::pg::Pg>::migrations(&crate::db::MIGRATIONS)
                .expect("embedded migrations")
                .iter()
                .map(|m| m.name().version().to_string())
                .collect();
        let mut sorted = embedded.clone();
        sorted.sort();
        let prefixes: Vec<String> = MIGRATION_PREFIXES
            .iter()
            .map(|p| p.version.to_string())
            .collect();
        assert_eq!(prefixes, sorted);
    }

    /// The pinned 1.0.x points still name this build's migrations, byte for
    /// byte. Fails when a shipped migration is edited.
    /// The CI guard for shipped schemas: the migrations up to every pinned
    /// release point are still the ones it shipped. A migration edited after
    /// it shipped, or a new one that sorts before a shipped point, changes
    /// that prefix's digest.
    #[test]
    fn shipped_schema_points_pin_their_migration_prefixes() {
        let shipped = LEGACY_SCHEMA_POINTS
            .iter()
            .map(|p| (p.migration, p.prefix_sha256))
            .chain(
                RELEASED_SCHEMA_POINTS
                    .iter()
                    .map(|p| (p.migration, p.prefix_sha256)),
            );
        for (migration, prefix_sha256) in shipped {
            let prefix = MIGRATION_PREFIXES
                .iter()
                .find(|p| p.version == migration)
                .unwrap_or_else(|| panic!("migration {migration} is gone"));
            assert_eq!(
                prefix.sha256, prefix_sha256,
                "the migrations up to {migration}, which a release shipped, changed: one was \
                 edited, or a new one sorts before it. A migration in a patch release must sort \
                 after everything main has already shipped (DEVELOPMENT.md, \"Releases\")."
            );
        }
    }

    #[test]
    fn a_backup_from_this_build_restores_as_it_is() {
        let current = current_schema();
        let m = manifest(
            env!("CARGO_PKG_VERSION"),
            "ignored",
            Some((current.version, current.sha256)),
        );
        assert_eq!(schema_point(&m), Ok(SchemaPoint::Current));
        // A manifest from before the point was recorded, by this build.
        let m = manifest(env!("CARGO_PKG_VERSION"), env!("NOSDESK_SCHEMA_HASH"), None);
        assert_eq!(schema_point(&m), Ok(SchemaPoint::Current));
    }

    #[test]
    fn a_1_0_backup_is_upgraded_from_its_last_migration() {
        let m = manifest("1.0.12", "0319c33351b4a3c4", None);
        assert_eq!(
            schema_point(&m),
            Ok(SchemaPoint::Earlier {
                migration: "20260618100000"
            })
        );
        let m = manifest("1.0.0", "bfd48f513ed7ebd7", None);
        assert_eq!(
            schema_point(&m),
            Ok(SchemaPoint::Earlier {
                migration: "00000000000000"
            })
        );
    }

    #[test]
    fn a_backup_from_an_earlier_recorded_point_is_upgraded() {
        let earlier = MIGRATION_PREFIXES[MIGRATION_PREFIXES.len() - 2];
        let m = manifest("1.1.0", "ignored", Some((earlier.version, earlier.sha256)));
        assert_eq!(
            schema_point(&m),
            Ok(SchemaPoint::Earlier {
                migration: earlier.version
            })
        );
    }

    #[test]
    fn an_unrecognised_or_newer_backup_is_refused() {
        let current = current_schema();
        // Same migration, different files: edited or a development build.
        let m = manifest("1.1.0", "ignored", Some((current.version, "0000")));
        assert!(matches!(
            schema_point(&m),
            Err(NotRestorable::Unknown { .. })
        ));
        let m = manifest("1.0.12", "0123456789abcdef", None);
        let refused = schema_point(&m).expect_err("unknown fingerprint");
        assert!(matches!(refused, NotRestorable::Unknown { .. }));
        assert!(
            refused.to_string().contains("Nosdesk 1.0.0 to"),
            "{refused}"
        );
        let m = manifest("99.0.0", "ignored", Some(("99990101000000", "abc")));
        assert!(matches!(schema_point(&m), Err(NotRestorable::Newer { .. })));
        let m = manifest("99.0.0", "0123456789abcdef", None);
        assert!(matches!(schema_point(&m), Err(NotRestorable::Newer { .. })));
    }

    #[test]
    fn the_scratch_database_url_names_the_scratch_database() {
        assert_eq!(
            with_database("postgres://u:p@db:5432/nosdesk?sslmode=require", "scratch"),
            "postgres://u:p@db:5432/scratch?sslmode=require"
        );
        assert_eq!(
            with_database("host=db user=u dbname=nosdesk", "scratch"),
            "host=db user=u dbname=nosdesk dbname=scratch"
        );
    }
}
