DROP POLICY IF EXISTS tickets_workspace_isolation ON tickets;
ALTER TABLE tickets NO FORCE ROW LEVEL SECURITY;
ALTER TABLE tickets DISABLE ROW LEVEL SECURITY;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM nosdesk_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE USAGE, SELECT, UPDATE ON SEQUENCES FROM nosdesk_app;
REVOKE USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public FROM nosdesk_app;
REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM nosdesk_app;
REVOKE USAGE ON SCHEMA public FROM nosdesk_app;
DROP ROLE IF EXISTS nosdesk_app;
